### ISSUE TITLE
Give users the ability to propose edits to pages (add versioning to restrooms)

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#126]
If they find something wrong with a restroom, let them send pending updates that only need to be approved. Better than having to make all the updates from the contacts.

**Comment by mi-wood** [comment]
This should have been autoclosed, but I messed up the linking

**Comment by DeeDeeG** [comment]
For the historical record:

The PR that implemented this was https://github.com/RefugeRestrooms/refugerestrooms/pull/530
