### ISSUE TITLE
Create contribution guide

### ISSUE THREAD

**Issue by strand** [RefugeRestrooms/refugerestrooms#137]
The README currently has a little info about our stack and testing practices, and a lot of uncaptured details about how to contribute, like [where to find assets](https://github.com/RefugeRestrooms/refuge_assets)

To complete this issue, we should 
- [ ] create a contributing.md
- [ ] link to it from the readme
- [ ] compile resources and guidelines for contributors in the contributing.md

**Comment by tkwidmer** [comment]
We should put this information on refugerestrooms.github.io

**Comment by mi-wood** [comment]
Closing in favor of https://github.com/RefugeRestrooms/refugerestrooms/issues/321 since contributing doc exists
