### ISSUE TITLE
Web performance improvements 

### ISSUE THREAD

**Issue by mathonsunday** [RefugeRestrooms/refugerestrooms#158]
I put refugerestrooms.com through Google's free PageSpeed insights tool and got this advice to improve our web performance: https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.refugerestrooms.org&tab=mobile

**Comment by mi-wood** [comment]
I'm going to close this for the time being and keep an eye on web performance (both through heroku and innocraft). If something becomes an issue, I'll create a specific issue to target one of these items.

**Comment by DeeDeeG** [comment]
Historical note:

Some recent things that hopefully should help:

- We switched from WEBrick to Puma: https://github.com/RefugeRestrooms/refugerestrooms/pull/442
- We activated static asset serving (still in `develop` branch/staging at the moment): https://github.com/RefugeRestrooms/refugerestrooms/pull/532
- Updated Rails and Ruby a few times, bumped lots of packages
