### ISSUE TITLE
Help OpenStreetMap make it easy to mark/find safe & accessible restrooms

### ISSUE THREAD

**Issue by thekyriarchy** [RefugeRestrooms/refugerestrooms#169]
https://github.com/twain47/Nominatim/issues/201
https://github.com/openstreetmap/iD/issues/2422

If OpenStreetMap could import our data, RefugeRestrooms could do much less work and operate more as a front-end to OSM and focus on gathering contributions from mappers everywhere and mobilizing people to convert gender exclusive restrooms to all-gender ones.

**Comment by tkwidmer** [comment]
Doesn't seem like OSM is that open to it, there was some conversation about this a long time ago, but they weren't interested. Closing for now.
