### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by mathonsunday** [RefugeRestrooms/refugerestrooms#170]
Whenever I try to run the app (ex. with pow) I get this error:

RuntimeError: Devise.secret_key was not set. Please add the following to your Devise initializer:

  config.secret_key = '-----'

Please ensure you restarted your application after installing Devise or setting the key.

I know we set the key in devise.rb, so I'm surprised to get this error. I get the same error when I change the key environment variable to the new key given in the error message and restart the app.

**Comment by kiesia** [comment]
I have this issue as well, I have made a pull request to fix the issue.

**Comment by kiesia** [comment]
Also just as a note, we are not all running OSX and we need to make sure the app works without pow etc.
