### ISSUE TITLE
Search by Address is Broken on iOS Safari and Chrome.

### ISSUE THREAD

**Issue by aliceyoung9** [RefugeRestrooms/refugerestrooms#188]
I type in an address, I hit search, then I actually get a bunch of restrooms near 1 Embarcadero Center, San Francisco, CA.

**Comment by mi-wood** [comment]
I just tested this using swiftkey. Since our app, swiftkey, and iOS have all had major updates, I'm going to assume something fixed this along the way. If anyone else notices an issue, we can reopen this.
