### ISSUE TITLE
Site doesn’t work without a leading www

### ISSUE THREAD

**Issue by backspace** [RefugeRestrooms/refugerestrooms#189]
In looking into that new issue, I typed `refugerestrooms.org` and got an empty Hover site. For nerds like me who type their own web addresses, it would make sense to at least forward `refugerestrooms.org` to `www.refugerestrooms.org`, or even more [to my taste](http://no-www.org/faq.php), the reverse hehe

**Comment by kiesia** [comment]
I'm still getting this error. DNS is not correctly configured for refugerestrooms.org:

This is correct, though a chained CNAME is not great, but nevermind. (Pointing to 107.20.253.181): 

```
; <<>> DiG 9.9.5-7-Debian <<>> www.refugerestrooms.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 58522
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 4, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.refugerestrooms.org.	IN	A

;; ANSWER SECTION:
www.refugerestrooms.org. 706	IN	CNAME	refugerestrooms.herokuapp.com.
refugerestrooms.herokuapp.com. 79 IN	CNAME	us-east-1-a.route.herokuapp.com.
us-east-1-a.route.herokuapp.com. 54 IN	A	107.20.253.181

;; AUTHORITY SECTION:
herokuapp.com.		248	IN	NS	ns-1378.awsdns-44.org.
herokuapp.com.		248	IN	NS	ns-1624.awsdns-11.co.uk.
herokuapp.com.		248	IN	NS	ns-505.awsdns-63.com.
herokuapp.com.		248	IN	NS	ns-662.awsdns-18.net.

;; Query time: 48 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Fri Jan 02 14:42:57 CET 2015
;; MSG SIZE  rcvd: 277
```

Whereas refugerestrooms.org is pointing to a totally different server (64.99.80.30):

```
; <<>> DiG 9.9.5-7-Debian <<>> refugerestrooms.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 39214
;; flags: qr aa rd ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;refugerestrooms.org.		IN	A

;; ADDITIONAL SECTION:
refugerestrooms.org.	577	IN	A	64.99.80.30

;; Query time: 3 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Fri Jan 02 14:44:51 CET 2015
;; MSG SIZE  rcvd: 64
```

**Comment by kiesia** [comment]
I'm also getting the same issue when querying OpenDNS.

**Comment by tkwidmer** [comment]
I'll look into it. I think the chained CNAME is how heroku does it, unfortunately. In their DNS instructions they direct you to list refugerestrooms.herokuapp.com in your DNS record.

**Comment by kiesia** [comment]
Oh yeah that shouldn't be the problem. It's not good practice regardless, but oh well.

**Comment by cllns** [comment]
Sorry to make this more complicated, but I just noticed
refugerestrooms.com and www.refugerestrooms.com are both now broken 
[from: https://github.com/RefugeRestrooms/refugerestrooms/issues/87]

Perhaps it's related?

**Comment by tkwidmer** [comment]
So I don't know what to say or do here. But here are screenshots of the relevant settings pages. 

#### Heroku Domain Settings
![screen shot 2015-01-21 at 11 39 46 am](https://cloud.githubusercontent.com/assets/5265597/5843565/3ffd0dda-a162-11e4-89c0-033816b2a117.png)

#### Hover DNS settings for .org
![screen shot 2015-01-21 at 11 37 24 am](https://cloud.githubusercontent.com/assets/5265597/5843571/48e255f4-a162-11e4-89c6-8f128f6d4d57.png)

#### Hover DNS Settings for .com
![screen shot 2015-01-21 at 11 37 50 am](https://cloud.githubusercontent.com/assets/5265597/5843574/50dc4620-a162-11e4-86fe-fb8d3403b401.png)

#### Hover, forwarding of .com to .org which should make the DNS for .com irrelevant. 
![screen shot 2015-01-21 at 11 37 59 am](https://cloud.githubusercontent.com/assets/5265597/5843587/6bd9634a-a162-11e4-9e8b-7ddf1605fb94.png)

**Comment by tkwidmer** [comment]
@cllns @kiesia

**Comment by cllns** [comment]
I'm not sure if you changed something, or maybe it was just a fluke earlier, but now both .com's work!

**Comment by kiesia** [comment]
www.refugerestrooms.org is now working for me too! Closing this, I'll keep an eye on it.

**Comment by tkwidmer** [comment]
welp. idk what i did. I futzed with them a little bit. Maybe was just taking longer to propegate

http://cdn.gurl.com/wp-content/uploads/2013/04/beyonce-hair-flip.gif

**Comment by kiesia** [comment]
Maybe it just needed to be saved again? Something was stuck, I don't think it was anything you were doin.

**Comment by kiesia** [comment]
@tkwidmer this is now pointing to hover again.. :frowning: Can you give me access to the DNS host so I can take a look?

**Comment by tkwidmer** [comment]
I dont think I can actually add you as an admin on hover. =/

**Comment by kiesia** [comment]
@tkwidmer sorry I did not see those images earlier. Hover domain forwarding is clearly not working! Just change the @ and * entries to CNAME to refugerestrooms.herokuapp.com, then it should work.

**Comment by kiesia** [comment]
Just read this long running saga, it looks like hover will support ANAMEs soon.

**Comment by kiesia** [comment]
Sigh. I'm very tempted just to set up a redirect on my server and we can point the @ record there..

**Comment by tkwidmer** [comment]
So to be clear, I need to add an * entry for CNAME?

There is already an @ entry. 

@kiesia
