### ISSUE TITLE
Redirect safe2pee.org

### ISSUE THREAD

**Issue by AndrewTheLott** [RefugeRestrooms/refugerestrooms#191]
safe2pee.org is no longer up and running but their existing [WordPress blog](http://safe2pee.wordpress.com/) and [Twitter](https://twitter.com/safe2pee) both point to that domain. There are some old links pointing that way too which just end up dying.

Since safe2pee have essentially endorsed this project as its successor it would be sensible to get access to that domain to point here instead. The domain is currently in "AUTORENEWPERIOD" status, so perhaps somebody should contact them to see what they'd approve?

**Comment by tkwidmer** [comment]
safe2pee was redirecting to refuge, but since it looks like their domain has expired that is no longer happening. Ill tweet at them and see whats up. If i have to take ownership of it via transer I can do that.

**Comment by tkwidmer** [comment]
I dont have the ability to do this.
