### ISSUE TITLE
Rendering issues in IE9

### ISSUE THREAD

**Issue by kiesia** [RefugeRestrooms/refugerestrooms#197]
Icon heights are looking pretty funky in IE9. 

![screenshot from 2015-01-30 12 57 14](https://cloud.githubusercontent.com/assets/783612/5975403/aad634ae-a880-11e4-885d-d9b7476f7507.png)

![screenshot from 2015-01-30 12 57 43](https://cloud.githubusercontent.com/assets/783612/5975405/b1156678-a880-11e4-989c-34968c24bd5e.png)

I also quickly checked IE11 but that seemed fine.

**Comment by katarinajuliana** [comment]
I got this!

**Comment by mi-wood** [comment]
Thanks @katarinajuliana!
