### ISSUE TITLE
Remove "Also on RefugeRestrooms" in Disqus comments

### ISSUE THREAD

**Issue by kiesia** [RefugeRestrooms/refugerestrooms#199]
This takes up a lot of space and is visually very confusing. Possibly useful if you live in SF, but for the rest of the world not so much. I don't need to see comments on toilets that are 2000km away. :smile:

**Comment by kiesia** [comment]
@tkwidmer if you give me the Disqus credentials I can do this.

**Comment by tkwidmer** [comment]
@kiesia I removed it -- but if you can give me yr discus account email I'll add you as a moderator too, so its not just under my own person account. Right now i'm the only mod for refuge Disqus.

**Comment by kiesia** [comment]
Awesome thanks @tkwidmer. I've emailed you my Dsiqus account.
