### ISSUE TITLE
Cannot access API at http://www.refugerestrooms.org/api/docs/

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms#203]
When I head to the API link, I get this error:

*Unable to read api 'restrooms' from path http://www.refugerestrooms.org/api/swagger_doc.json/restrooms.json (server returned undefined)*

**Comment by tkwidmer** [comment]
Looks like its a bug in Grape / Swagger

http://stackoverflow.com/questions/27656851/grape-swagger-unable-to-read-api-users-from-path-url-server-returned-undefi

**Comment by tkwidmer** [comment]
Looks like an upgrade to 0.9 will fix it maybe?

**Comment by kiesia** [comment]
PR #210
