### ISSUE TITLE
Restroom state?

### ISSUE THREAD

**Issue by kiesia** [RefugeRestrooms/refugerestrooms#209]
So I'm working on #126 (still) and am wondering about restroom state. I currently have a simple boolean for "approved", but this won't cut it. I'm also wondering what else we might want to use state for? For instance, instead of destroying records, we could just mark them as hidden.

This is what I'm imagining. A new Restroom is created or updated and marked as 'pending'. Admin either marks this as 'approved' or 'rejected'. Only approved restrooms will be displayed.

What do you all think?

**Comment by tkwidmer** [comment]
I think that sounds good. 
May be useful for hiding and stuff down the road.

**Comment by kiesia** [comment]
Great thanks, I'll start with pending, approved and rejected.
