### ISSUE TITLE
How do I fetch all of the Restroom records at a certain endpoint?

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms#211]
I attempting to fetch all of the records in my code using the `by_date` endpoint. I used to specify a `per_page` limit of `10000`, however that now gives me the message `{"error":"per_page must be less than 100"}`. Not providing a limit caps the result at 10 records.

How would I get all of the records - or at least thousands - instead of being capped by 10 or 100?

**Comment by cllns** [comment]
Why do you need to fetch all of them? Shouldn't 100 be enough for most end-user requests?

Or is this for development / a local copy of the DB?

**Comment by hkellaway** [comment]
Yes, it's for development

**Comment by cllns** [comment]
Maybe @tkwidmer can give you access to Heroku, where you can take a dump of the DB? #196 
Though, that gives you the whole DB, not just one endpoint.

**Comment by tkwidmer** [comment]
@hkellaway If you give me yr heroku email ill add you on there. We should probably figure out a long term solution to this. Even if its like a /api/dev/all_restrooms endpoint.

**Comment by hkellaway** [comment]
the whole DB is fine. @tkwidmer: my first-name dot last-name @ gmail

**Comment by mi-wood** [comment]
Closing this. Feel free to reopen if someone wants this as a feature
