### ISSUE TITLE
Question: What is the threshold for Refuge considering a restroom as negatively rated?

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms#213]
i.e. when does the rating percentage go from green to red? 50%?

**Comment by cllns** [comment]
70% to 100% is green
50% to 70% is yellow
0% to 50% is red

From:
https://github.com/RefugeRestrooms/refugerestrooms/blob/ac1794bfc5227b79eb1bd22bf3eb61b48099fba7/app/models/rating_level.rb#L5

**Comment by hkellaway** [comment]
Thanks @cllns
