### ISSUE TITLE
Positioning and the future of Refuge

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#215]
I want Refuge to become about more than restrooms at some point.  Restroom access is really important. But there are a lot of other issues and places in life that trans people (and especially trans women) need a Refuge for. 

The first that comes to mind is housing. Currently the only thing filling this need is http://www.transhousingnetwork.com/ -- A tumblr created by jobhaver to try to to connect trans people who need a place to stay with a place to stay. However, it's hard to search. Posts don't get updated. It's mostly a place for just current listings. Which is great. But it would be great to write the trans version of couchsurfing https://www.couchsurfing.com/ -- Where posts could be sorted by location and time - posts can be updated, removed. People can post housing needed / housing wanted. I wouldn't want to fully map this stuff out for privacy reasons. Ie, people wouldn't want to post their addresses. But posts can show up in a per city / distance based list. 

Refuge Restrooms is/was great. But it's a small scope. How can we expand that scope? What other types of refuge can we provide access to?

**Comment by tkwidmer** [comment]
It's this kind of jump that could get Refuge some funding / help be able to pay some people (hopefully trans people trying to learn how to code), to do some work on the site.

**Comment by cllns** [comment]
:+1:

**Comment by nataliegroman** [comment]
I'm still always down for more design. I haven't touched it in about 8
months, but the site for the most part looks pretty solid except for some
oddball contributions from some other people. I might take a day and head
to SF to hang with you about an upcoming funding campaign (maybe patreon?)

On Wed, Feb 18, 2015 at 11:18 AM, Teagan <notifications@github.com> wrote:

> It's this kind of jump that could get Refuge some funding / help be able
> to pay some people (hopefully trans people trying to learn how to code), to
> do some work on the site.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RefugeRestrooms/refugerestrooms/issues/215#issuecomment-74928504>
> .
>



-- 
Natalie Roman - Ball State University - Telecommunications - Class of 2015
Collective Digital Studio - Network Development Intern
Student Recreation and Wellness Center - Web Manager
Gamma Rho Lambda - Co-founder/Alumni
765.713.9558
http://natalieroman.com

**Comment by jotter4000** [comment]
I'm down but it's easiest for me to do it at a meetup, not really on my
own. If anyone wants to pair or meet somewhere I'm down :D

**Comment by nataliegroman** [comment]
What I am thinking is that for a long time, trans people have been having
issues amalgamating useful narrative info into one specific place, without
it being ridiculously dated. What was once comprehensive (TG Roadmap) is
massively problematic and ran by a TERF lunatic. To modernize this
information, curate articles, videos, searchable engines, and more, we
could finally use our team to make a site that is for us, and specifically
for us. We would need the aid of transmasculine people to help further this
along, as a lot of the resources are very seperate. A binder swap/giveaway.
A clothes board. Free trans affirmative community counselors in your area.
Endos that have treated trans people. Prices for that. Comprehensive
surgery site, excluding pictures, for obvious reasons.

The HitchHiker's Guide to Gender Dysphoria.

On Sat, Feb 21, 2015 at 2:52 PM, jotter4000 <notifications@github.com>
wrote:

> I'm down but it's easiest for me to do it at a meetup, not really on my
> own. If anyone wants to pair or meet somewhere I'm down :D
>
> On Fri, Feb 20, 2015 at 2:54 PM, nataliegroman <notifications@github.com>
> wrote:
>
> > I'm still always down for more design. I haven't touched it in about 8
> > months, but the site for the most part looks pretty solid except for some
> > oddball contributions from some other people. I might take a day and head
> > to SF to hang with you about an upcoming funding campaign (maybe
> patreon?)
> >
> > On Wed, Feb 18, 2015 at 11:18 AM, Teagan <notifications@github.com>
> wrote:
> >
> > > It's this kind of jump that could get Refuge some funding / help be
> able
> > > to pay some people (hopefully trans people trying to learn how to
> code),
> > to
> > > do some work on the site.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/RefugeRestrooms/refugerestrooms/issues/215#issuecomment-74928504
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Natalie Roman - Ball State University - Telecommunications - Class of
> 2015
> > Collective Digital Studio - Network Development Intern
> > Student Recreation and Wellness Center - Web Manager
> > Gamma Rho Lambda - Co-founder/Alumni
> > 765.713.9558
> > http://natalieroman.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/RefugeRestrooms/refugerestrooms/issues/215#issuecomment-75334754
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RefugeRestrooms/refugerestrooms/issues/215#issuecomment-75397653>
> .
>



-- 
Natalie Roman - Ball State University - Telecommunications - Class of 2015
Collective Digital Studio - Network Development Intern
Student Recreation and Wellness Center - Web Manager
Gamma Rho Lambda - Co-founder/Alumni
765.713.9558
http://natalieroman.com

**Comment by mi-wood** [comment]
Any sort of comprehensive healthcare database. It'd definitely have to start small and would be tough to keep up to date, but there are some things that would be exceptionally helpful. Trans friendly therapists, providers/plans that have the best trans coverage, etc. This info is currently a bit scattered if available/up to date at all. This would be a heavily crowdsourced effort also, since it doesn't have a seed like with safe2pee

**Comment by mi-wood** [comment]
Also for those who are in SF bay, Take 5 cafe in Berkeley seemed like that would be happy to host a hack day/meeting and they are trans/queer friendly :)
