### ISSUE TITLE
Restrooms not showing up in listings after they are created.

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#216]
I noticed this today walking a friend through the creation of a Restroom.

The restroom was created and is sitting in the database. It looks like this is happening because the geolocation is broken on Restroom create. This is really a bad issue, because it looks like we have restrooms that are created with no Lat/Long which means we can't map them when people search locations. Maybe Geocoder gem is broken? Will take a little bit of research to figure out.

For reference, here are two screenshots of two recent bathroom listings, which did not geocode correctly.

This fix will require two actions.
1) figure out why bathrooms are not geocoding correctly. The specs are still passing.
2) Run a script to geocode bathrooms in the database which do not have lat/long listings

![screen shot 2015-02-22 at 11 53 29 am](https://cloud.githubusercontent.com/assets/5265597/6320071/8b3d8a32-ba89-11e4-9ce1-9bfb8d81b34d.png)
![screen shot 2015-02-22 at 11 49 37 am](https://cloud.githubusercontent.com/assets/5265597/6320072/8d2d6ff6-ba89-11e4-9685-66d54b4939e0.png)

**Comment by tkwidmer** [comment]
There are 11 bathrooms that do not have latitude listings. Found using running `Restroom.all.where(:latitude => nil)`  on production.

**Comment by tkwidmer** [comment]
This seems to have been fixed by the most recent release. -- i'm going to run a script to try to geocode stuff that wasn't geocoded correctly.

**Comment by hkellaway** [comment]
@tkwidmer does this mean i should re-create the Restroom seed for the iOS app?

**Comment by tkwidmer** [comment]
You will just be missing a couple of bathrooms, (and any new ones that are created).

**Comment by hkellaway** [comment]
any new one's created?

**Comment by tkwidmer** [comment]
The script for this fix is complete.
