### ISSUE TITLE
"Uncaught Security Error" from Disqus when looking at a restroom

### ISSUE THREAD

**Issue by kevjames3** [RefugeRestrooms/refugerestrooms#221]
Example: http://www.refugerestrooms.org/restrooms/67

Chrome debugger gives the following error:

Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:3000" from accessing a frame with origin "http://disqus.com". Protocols, domains, and ports must match.

**Comment by tkwidmer** [comment]
I don't know if we actually have control over this.
