### ISSUE TITLE
King\'s Museum

### ISSUE THREAD

**Issue by TazeTSchnitzel** [RefugeRestrooms/refugerestrooms#229]
Just saw a restroom with that title on the map. Is there/was there double-escaping of data being put into the database? The backslash is probably not deliberate.

**Comment by TazeTSchnitzel** [comment]
Apparently this only happens in the iOS app:

![](http://i.imgur.com/LbUvF3C.jpg) ![](http://i.imgur.com/AjbuJUc.jpg)

On the website, it doesn't:

![](http://i.imgur.com/F9xyZip.png)

http://www.refugerestrooms.org/restrooms/4348

This is puzzling. Why wouldn't it happen on the site? Are magic quotes happening somewhere? D:

**Comment by hkellaway** [comment]
@TazeTSchnitzel good catch! i'll look into it

**Comment by tkwidmer** [comment]
Going to close this on the web, since it looks like its an issue on iOS side and not web. Thanks @TazeTSchnitzel and @hkellaway
