### ISSUE TITLE
Vagrant improvements

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#231]
- Add swapspace and see if this fixes the memory allocation issues. This will also allow users will less ram on their host to use 512MB
- Add rake wrapper to start server, bundle install, etc.

**Comment by dannypaz** [comment]
@mi-wood @tkwidmer What features (other than starting a server, which already exists) would we want to see? Off the top of my head....

1. Start server (done)
2. Bundle update
3. SSH (nice to have consistency)
4. DB migration

Bundle install should be covered by `provision` although we might need to add more? documentation around that?

**Comment by mi-wood** [comment]
@dannypaz this ticket might be outdated as the wrapper already exists. Maybe the documentation needs to be clearer than you can run any command from the wrapper script?

**Comment by dannypaz** [comment]
@mi-wood that sounds good (The docs are pretty good for it). Do you think it would be beneficial to have a few stand-alone commands?

Either way, it looks like we are safe to close this issue.
