### ISSUE TITLE
Social buttons obstructing 'Add A Restroom' button on Chrome

### ISSUE THREAD

**Issue by waseem18** [RefugeRestrooms/refugerestrooms#232]
On chrome, when the site gets loaded, social buttons are obstructing the 'Add A Restroom' button. 
![bug](https://cloud.githubusercontent.com/assets/5843007/6867913/a133d188-d4ac-11e4-908b-f4518b865fbc.PNG)

**Comment by tkwidmer** [comment]
This is actually not a browser issue, it's the side of your screen. the buttons are tied to the bottom of the screen, they should actually be pinned to the bottom of the page div. Should be an easy fix.

**Comment by tkwidmer** [comment]
If you scroll down you should be able to see the button in full.

**Comment by waseem18** [comment]
I guess it's a bit of browser issue. Because there is some space between social buttons and 'Add restroom' button in both IE and Mozilla. The obstruction is only on Chrome. By the way we can see the full button by scrolling down. But I feel that when the site gets loaded initially there should be some space between both buttons so that the user doesn't need to scroll down to click on 'Add a Rest room' button.

**Comment by cboyden** [comment]
The obstruction happens depending on the height of the browser window and how far down you've scrolled. 
![screen shot 2015-06-02 at 8 26 32 pm](https://cloud.githubusercontent.com/assets/725267/7952145/1b1f6e6a-0966-11e5-9938-e10ebfc7d51b.png)
This screenshot is Firefox on OSX with a short window. Social links block the app store link.
