### ISSUE TITLE
Add if a restroom has a baby changing station

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#233]
Got this email in through the contact us link

> Hi! I want to thank you so much for what you do and for offering the use of this website and I note I don't require this website (I'm cisgender) but am incredibly grateful this is here. You should be proud, so proud for giving safety for people who just need to go to the bathroom. Thank you so much--you are awesome!!!
> 
> Now to business: I would like to see this website integrate into it whether the restroom has a baby-changing station or not. This was called to my attention when I saw a Change.org petition to a certain company by Ashton Kutcher, who is a dad, and he was requesting that the men's restrooms at the company have a baby changing station for parenting. I then realized that they discriminated against him for being a dad who wanted to take care of his child. So then I realized that this website didn't have a baby-changing indicator for its restrooms on the site. I would greatly appreciate the addition of this feature to the editing section of the page to both keep "bathroom owners" accountable and to give a sense of comfort/less anxiety for trans_, genderqueer, and intersex parents. I am proud of this website for being disability-friendly, too! That is very smart and accommodating. I love you all to death figuratively for having this website. I am incredibly grateful. The good reputation of this website will only get better if baby-changing stations are added. Not only would this be trans_ (umbrella) friendly and disability-friendly, the page would be "parent-friendly" and by extension, "baby-friendly." This would be great and I highly recommend it.

**Comment by azelma** [comment]
I'll take this.

**Comment by tkwidmer** [comment]
Closed by #248
