### ISSUE TITLE
Typo.

### ISSUE THREAD

**Issue by aitchabee** [RefugeRestrooms/refugerestrooms#237]
Hi!  I would submit a PR for this, but I'm not sure where the file is that needs to be updated.

On the About page, I believe there is a missing word. One of the sections is "What can we to help?". I thought perhaps that could be "What can we do to help?".

**Comment by cllns** [comment]
Here's the file, for whoever wants to take this! 

https://github.com/RefugeRestrooms/refugerestrooms/blob/master/config/locales/about.en.yml#L12

**Comment by aitchabee** [comment]
Here is the PR: https://github.com/RefugeRestrooms/refugerestrooms/pull/238 :sparkling_heart:

**Comment by cllns** [comment]
yay!! thanks!
