### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms#244]
Do we have anything setup to take donations? Or is this something we want to do? Just received an email on the android app from a user who would like to contribute.

**Comment by mDantas** [comment]
hey @hissingpanda just posting for reference should this be something everyone wants to do https://www.paypal.com/webapps/mpp/get-started/donate-button

**Comment by tkwidmer** [comment]
I got kind of overwhelmed trying to figure out the best way to do this. Ultimately it has to come to one person who then has to report it as income to the IRS, unless we have an official 501c3 sponsor. And a channel set up that way for donations.

**Comment by mi-wood** [comment]
I think I'm going to close this for now. It's an ongoing discussion that we can chat about in slack or something.
