### ISSUE TITLE
Resources link turns grey after click

### ISSUE THREAD

**Issue by valeriecodes** [RefugeRestrooms/refugerestrooms#247]
If you click on the "Resources" arrow and then mouse away from the link, the link text turns grey and is hard to see.
<img width="192" alt="screen shot 2015-10-15 at 7 23 44 pm" src="https://cloud.githubusercontent.com/assets/5439589/10530141/5cf95c1c-7372-11e5-9d5a-93e4cf5cc0cb.png">

**Comment by mDantas** [comment]
Hey @valeriecodes, what browser? I'm looking on Chrome for mac and it looks fixed?

**Comment by dunn** [comment]
I was just able to reproduce on Opera 36.0.2130.32 with the current `develop` branch.

**Comment by dunn** [comment]
If you click the other nav links then move the cursor away before the page loads, I see the same behavior.

**Comment by dunn** [comment]
IDK if it's a bug in Bootstrap or in the browsers but the anchor color doesn't seem to be getting overridden correctly.

**Comment by Hkly** [comment]
https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/assets/stylesheets/nav.css.scss#L17-L20

I think adding a `&:focus` color as well will fix the grey.

**Comment by dunn** [comment]
I was going to give that a shot, but I can't reproduce this anymore.

**Comment by Hkly** [comment]
I'll give it a shot, I can still reproduce it.

**Comment by tkwidmer** [comment]
#275 should fix this.
