### ISSUE TITLE
Can't Add Restrooms

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms#256]
I've gotten several emails from the android app recently about users unable to add restrooms. When I tried to add a restroom on the site I kept receiving this error:

"We're sorry, but something went wrong. If you are the application owner check the logs for more information."

Any ideas?

**Comment by mi-wood** [comment]
@tkwidmer this is probably (definitely) our heroku row limit. Any idea how much spam is sitting in there? I wonder if that would buy us a ton of space? I don't have admin access.

Alternatively, I will pay for upgrading this, but only the app owner has permissions to do so.

**Comment by tkwidmer** [comment]
ack, woah, i missed this. It needs to be upgraded. I'll try to figure out how to do this week. @mi-wood @hissingpanda I don't think it can be done on the web, I remember that much.

**Comment by tkwidmer** [comment]
As of Thursday March 24th, I've updated the database to a Hobby DB costing 9$ a month.
