### ISSUE TITLE
Location Services Disabled; Tell them they need to enable.

### ISSUE THREAD

**Issue by cs09g** [RefugeRestrooms/refugerestrooms#264]
os: window 7
web browser: latest chrome

when click search button with no query, refreshing animation starts with no reaction.
at least it should show what do i do, and stop the animation because it does not search anything.

**Comment by Hkly** [comment]
What's the expected behavior when searching without a query? The pull request referencing this https://github.com/RefugeRestrooms/refugerestrooms/pull/269 seems to imply that it searches the current location if no query is entered, but when I try that I'm just left spinning.

**Comment by cs09g** [comment]
It does show the message that a query should be entered, but spinning icon doesn't stop.

**Comment by Hkly** [comment]
Ah so it looks like you have location services blocked or disabled on your browser. When location services is enabled, searching with no query does a search on your current location.

A fix for this would maybe be adding a message letting users know they need to enable location services. And stop the animation spinning too :P

**Comment by cs09g** [comment]
@Hkly Right! I guessed so. That fix you just mentioned would be great.

**Comment by DeeDeeG** [comment]
I believe this is fixed by #359.
