### ISSUE TITLE
Feature Request: optional photo

### ISSUE THREAD

**Issue by strixcuriosus** [RefugeRestrooms/refugerestrooms#265]
I notice that the "submit a new restroom" form in the web app does not have an option for image input. I have encountered some delightfully inclusive restroom doors, and I'd be interested in adding a refugerestrooms feature to document photos of restroom door signs.

Photos may also be helpful for clarifying or providing additional detail to directions. For example, saying "the restroom is located next the Landmark X inside of Venue Y" could be enhanced by having a photos of Landmark X as well as of the outside Venue Y.

**Comment by pedrozan** [comment]
Hello, I think this would be nice. Can I develop this feature?

**Comment by tkwidmer** [comment]
@pedrozan absolutely.

**Comment by pedrozan** [comment]
Thanks @tkwidmer I'll fork and start ASAP

**Comment by tkwidmer** [comment]
@pedrozan awesome, thank you!

**Comment by DeeDeeG** [comment]
Someone managed to get a picture posted in the comments section.

http://www.refugerestrooms.org/restrooms/22898

I didn't know that was possible... The fact that this issue exists and has 4 thumbs up suggests most people wouldn't think they could add a photo in the comments. Maybe there should be a note encouraging people to add/informing people they can add photos in the comments? Or maybe a feature allowing a dedicated "official" photo/photos by the submitter is worthwhile regardless of it being doable in the comments section? 

(Disqus is lazy-loaded anyway, only showing up when a user scrolls down, so people may not see the photos in the comments section if they aren't deliberately loading the comments.)

**Comment by mi-wood** [comment]
@DeeDeeG this seems totally reasonable to me. offloading the photos to disqus seems kinda nice imo. Maybe the task should be putting that in the faq or post submission as a fyi.

@pedrozan have you started working on this yet?

**Comment by pedrozan** [comment]
@mi-wood  I managed to find time to start, but now I'm having difficulties to find the time to finish it =P

**Comment by mi-wood** [comment]
Let's maybe add this to the FAQ and close it :)

**Comment by pedrozan** [comment]
@mi-wood maybe its best, sorry for not being able to finish this =/
