### ISSUE TITLE
FAQ for Restroom Hosts

### ISSUE THREAD

**Issue by ams0026** [RefugeRestrooms/refugerestrooms#272]
Hi All -- 

I'm new to the project and have been looking around for a way I can contribute. One thing I notice is that you don't have a FAQ for business owners/restroom hosts who find themselves on the list. I would like to take a first pass at that. 

Roughly I'd like to tell business owners: 
1.) How they got on this list (Someone used your restroom and thought you should be listed)
2.) Tips on being a good host 
3.) Why safe restrooms are an issue
4.) What reviews mean
5.) How to have your site removed

I would love feedback on whether y'all think this is a need. Thanks!

**Comment by ams0026** [comment]
I'm not sure how to take this issue but I'm going to get started on it.

**Comment by t-walker** [comment]
I think a FAQ page would be great! Maybe there could be a sign that includes some printable materials that or ability to order cooler signage so that they can be proud of their bathroom and make it more obvious.

**Comment by mi-wood** [comment]
I dug up some resources for work a while back, but it looks like I lost them when I switched my slack account :( I'll try to find some again and post them when I get a chance.

**Comment by teddynicholas** [comment]
I'm also new to the project though I've been watching it for a while. I can help with some design aspects of the project if that's necessary. And I'd also love to help with the composition of the FAQ as well.

**Comment by tkwidmer** [comment]
Thats great. We do have some printable signage on the site. As far as I'm concerned we can start writing the FAQ here, and once we have some good answers we can make a PR

**Comment by tkwidmer** [comment]
@ams0026

**Comment by bbax412** [comment]
Hi everyone!  Took a stab at these here at Hack Night -- all edits are most welcome!  Feel free to spin up into a FAQ and adjust as you'd like :)

**1) What is Refuge Restrooms?**
REFUGE is a web application that seeks to provide safe restroom access for transgender, intersex, and gender nonconforming individuals.  Read more about us on our [About page](https://www.refugerestrooms.org/about).

**2) How did my facility get on this list?**
Someone used your restroom and wanted to submit your location as a resource.  All our data is crowd-sourced and user-submitted.

**3) How can I be a good host?**
Thanks for asking!  Often, REFUGE visitors just hope to make a quick stop and be on our way, and like any other visitor, potentially support your business or location while we're there.  Friendly staff and good experiences can go a long way in getting some love for your location in the reviews section of the app (more on that below!)

**4) Why safe restrooms are an issue**
Using the restroom is an everyday activity that can be difficult for members of our community to navigate -- especially when visiting areas outside of their daily routines.  That's where our mapping project comes in.  A recent [survey](http://static1.squarespace.com/static/54f76238e4b03766696d8f4c/t/5782a8d9197aeaa57b589608/1468180715744/USTS-Preliminary-Findings-July-2016-2.pdf) revealed that, in the past year:

- 59% of respondents avoided using a restroom for fear of confrontation
- 31% avoided eating or drinking while out, to avoid having to use the restroom
- 24% had their presence in the restroom questioned
- 12% had been harassed, attacked, or sexually assaulted in a restroom
- 9% had been denied restroom access
- 8% had developed a kidney issue or urinary tract infection from avoiding bathroom usage

source: http://static1.squarespace.com/static/54f76238e4b03766696d8f4c/t/5782a8d9197aeaa57b589608/1468180715744/USTS-Preliminary-Findings-July-2016-2.pdf 

**5) What reviews mean**
Reviews help visitors share experiences with each other about the location.  We encourage visitors to share as much information as we have about each location on the map.

**6) How to have your site removed**
We hope you'll consider keeping your listing; it can mean a lot for people's health and wellbeing.  However, if you'd rather not be listed, use our contact form to request a removal and our volunteers will work on it as soon as we can (this is an open source project so all work is done by volunteers).

**Comment by mi-wood** [comment]
I'll go ahead and add a new page to link from the FAQ.
