### ISSUE TITLE
Admin access to edit restrooms

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms#284]
Does anyone check the emails for the "contact us about this post" contact form? Or has an updated database just not been deployed for awhile?

I receive a lot of requests to fix bathroom addresses from the android app and then submit them through this form. Is there a better way to go about this, or am I able to access the database myself?

**Comment by tkwidmer** [comment]
https://github.com/RefugeRestrooms/refugerestrooms/issues/126 exists, but stalled.

**Comment by tkwidmer** [comment]
I'm going to close this as a duplicate of #126. Admin access exists, and there are like 5 or 6 people who had volunteered to man this, but they have dropped off.
