### ISSUE TITLE
Heroku Server is down

### ISSUE THREAD

**Issue by hissingpanda** [RefugeRestrooms/refugerestrooms#285]
The heroku server is down at http://www.refugerestrooms.org/

"Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

**Comment by backspace** [comment]
This is surely [this issue](https://status.heroku.com/incidents/1059), which I believe relates to an S3 outage.

**Comment by tkwidmer** [comment]
This is due to S3 outage.

**Comment by tkwidmer** [comment]
https://status.heroku.com/incidents/1059

**Comment by hissingpanda** [comment]
Thanks for the info. It's back up now.

**Comment by tkwidmer** [comment]
We are back up. http://www.refugerestrooms.org/
