### ISSUE TITLE
Join the Slack

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#286]
I started a slack for Refuge contributors. You should join it.

Hoping this will be a good way for us to stay connected, and hopefully improve our work on Refuge Restrooms. If you are a contributor, or want to be a contributor, you should join the slack group

https://refugelgbt.slack.com/shared_invite/MTU0MjkzOTg5MzM0LTE0ODk0MjQ2NDQtZDU5MGFhYjhmZg

**Comment by mi-wood** [comment]
@tkwidmer this link is expired. Can you update and/or add me as an admin please :)

**Comment by jacindaz** [comment]
@tkwidmer Can you also add me as well? Thank you!

**Comment by tkwidmer** [comment]
updated link @jacindaz https://refugelgbt.slack.com/shared_invite/MTU0MjkzOTg5MzM0LTE0ODk0MjQ2NDQtZDU5MGFhYjhmZg

**Comment by tkwidmer** [comment]
The links are only good for one week

**Comment by mi-wood** [comment]
Maybe we can just say to make a github issue if you want to be added to the slack? I don't know if there's an easier way. Would like to close this though :)

**Comment by mi-wood** [comment]
Going to close this and maybe add something to the readme
