### ISSUE TITLE
Upgrade Rails to 5.1

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#287]
Rails has been upgrade. We need to try to stay current.

### Upgrade from 4.2 -> 5.0
http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0

### Upgrade from Rails 5.0 -> 5.1
http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1

**Comment by dannypaz** [comment]
I've been doing a little bit of research on our upgrade path. Here is some info

#### Gems to update

- rails 
- coffee-rails 
- dotenv-rails 
- quiet_assets (Removal)
  - See more info [here... deprecation](https://github.com/evrone/quiet_assets#deprecation)
- devise 
- jquery-rails
- turbolinks
- rack-contrib (See below)

#### Blockers

`rack-contrib` does not work with Rack 2, which is required for Rails 5. See more [here](https://github.com/rack/rack-contrib/pull/129). We can either fork this library and apply the patch OR we remove Grape for Rails 5 API.

**Comment by dannypaz** [comment]
@tkwidmer I have absolutely no idea what files can be removed from the repo, so i'll probably need some help in identifying these

**Comment by mi-wood** [comment]
Deployed at https://refuge-production.herokuapp.com/ !!

**Comment by tkwidmer** [comment]
Now just to get from 5.0 to 5.1!

**Comment by mi-wood** [comment]
fyi, this is currently blocked due to a transitive dependency between rails and devise. Will probably just wait for a release of devise
