### ISSUE TITLE
Upgrade Heroku Ceder Stack

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#288]
# Context

Heroku has depricated Ceder-10 which is what RefugeRestrooms is on. We need to update heroku to Ceder-14.

https://devcenter.heroku.com/articles/cedar-14-migration

<img width="670" alt="screen shot 2017-03-02 at 11 30 17 am" src="https://cloud.githubusercontent.com/assets/5265597/23523410/a30b8dfa-ff3b-11e6-8edb-d5c1ff2a930e.png">

**Comment by tkwidmer** [comment]
I'm planning to try to take this in the upcoming hack day

**Comment by tkwidmer** [comment]
https://github.com/RefugeRestrooms/refugerestrooms/issues/297 Needs to be resolved before we can deploy again.

**Comment by tkwidmer** [comment]
Something about Piwik or our setup of it is blocking the application from functioning on the new Heroku Cedar-14. I reverted some of the work in #206 and was able to get the app functioning for the most part. The maps are still broken on https://refuge-staging-14.herokuapp.com/, but it's in better condition. I'm using a test branch to try to do this work. I'll have to disable Piwik to get deploys back working.

**Comment by tkwidmer** [comment]
Now that #327 is merged, and #322 is closed. I think we may be good to go on the switch over

**Comment by mi-wood** [comment]
Yay this is deployed!
