### ISSUE TITLE
Guidelines for setting up dev environment could be clearer. 

### ISSUE THREAD

**Issue by maecapozzi** [RefugeRestrooms/refugerestrooms#290]
I think that it would be useful to add a bit more clarification on setting up vagrant -- I ssh'ed into vagrant, and then tried to copy and paste the commands below, only to realize that `rake vagrant:shell['rails s -b 0.0.0.0']` was within the shell. 

I would suggest that we specify that if someone was going to develop while logged into vagrant, they just use the command `rails s -b 0.0.0.0` if the have ssh'ed in, otherwise, use this command: `rake vagrant:shell['rails s -b 0.0.0.0']`

**Comment by cllns** [comment]
Thanks! I agree that should be more clear. Can you open a PR? :) it's fine if not

**Comment by maecapozzi** [comment]
Yes! Planning on it. I wanted to leave this here as a reminder for myself :)

**Comment by maecapozzi** [comment]
@cllns, here is the PR: https://github.com/RefugeRestrooms/refugerestrooms/pull/291
