### ISSUE TITLE
Need Facilitators for Mar. 13th Hack Night

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#294]
Hey all!

Right now we have about 20 RSVPs for next Monday not including folks from Optimizely that will be joining. Ideally, I'd like to have about a 1:5 facilitator to contributor ratio so people can get the proper time setting up their environments and getting familiar with the code base.

With Teagan and I, I'm looking for about 3 more people that have worked on the codebase and are willing to help! Feel free to respond on this post or message me in our new slack :)

Mikena

**Comment by mi-wood** [comment]
Event invite for reference: https://www.eventbrite.com/e/refuge-restrooms-hack-night-tickets-32423804472

**Comment by tkwidmer** [comment]
Yes please, if you are local, it would be wonderful to have you come by.
