### ISSUE TITLE
Guess Your Location does not return valid nearby restrooms

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#295]
<img width="590" alt="screen shot 2017-03-13 at 8 04 54 pm" src="https://cloud.githubusercontent.com/assets/5265597/23884178/777bc81c-0828-11e7-9eb9-583d7570a98c.png">

The Guess your location tool should show stuff nearby your location by distance order, currently its showing stuff on the opposite side of the country. 

Related PRs: https://github.com/RefugeRestrooms/refugerestrooms/pull/112
https://github.com/RefugeRestrooms/refugerestrooms/pull/110
https://github.com/RefugeRestrooms/refugerestrooms/pull/107

**Comment by DeeDeeG** [comment]
I think searching by lat & long is broken, but only with a bad search query. I would infer that the guess button is generating a bad search query.

- This URL works fine (just a typical restroom search in the search box): http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958&search=Text+Search%2C+Plantsoen%2C+Leiden%2C+Netherlands

- When I edit the URL, and remove everything but lat & long I get the same results as the guess button: http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958 it doesn't work.

- However, editing the URL to have lat and long, with `&search=""` at the end makes it work properly: http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958&search=%22%22

**Comment by DeeDeeG** [comment]
Think I figured it out. Or at least found a workaround:

Compare: http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958&nearby=true (broken, and resembles the current guess button behavior)

http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958&search=%22%22&nearby=true (working, modified version of the current guess button behavior)

http://refuge-production.herokuapp.com/restrooms?utf8=%E2%9C%93&lat=52.1540341&long=4.501732299999958&search=%22%22 (same as above, but without `&nearby=true`)
