### ISSUE TITLE
How do we share secrets/accounts?

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#306]
We should look into using a shared secret DB for some of our administrative keys. For accounts that allow multi-user access (ex. heroku) we should use that and make sure at least a few users have access to it. Otherwise, we should have somewhere to grab credentials from.

**Comment by juliofarah** [comment]
Hi there!
Hope you're doing great.

Please, correct me if I got it wrong, but I don't believe you need a secret DB (if you're concerned only about sharing passwords and access keys - `.pem` files).

In my current project, we currently use `git-crypt` as a solution for sharing sensitive information such as passwords and access keys in a secure way.
All the passwords are checked in with the code, but they're under a gpg encrypted directory.

Please, take a look at the documentation: https://github.com/AGWA/git-crypt

It basically consists in a trusted team member signing a gpg key to allow someone else to decrypt the files.

Hope it helps :)

**Comment by mi-wood** [comment]
Thanks @juliofarah! I'll take a look into when I get a chance!

**Comment by DeeDeeG** [comment]
There is something kinda similar to this in Rails 5.1, but I'm not sure if that covers the whole set of secrets/passwords you're referring to, @mi-wood.

http://edgeguides.rubyonrails.org/5_1_release_notes.html#encrypted-secrets

**Comment by mi-wood** [comment]
An FYI on this, since I did this. I have a family plan for 1password and shared a vault with @tkwidmer. This should suffice for the time being. I think they recently introduced some sort of plan for nonprofits/charities, so if we ever need to upgrade we can look into that.

**Comment by DeeDeeG** [comment]
Relatedly, we could set up a "Heroku Team" to share access to the Heroku instance, if need be. Seems very similar to "Organizations" here on GitHub.

**Comment by mi-wood** [comment]
@DeeDeeG We're using this currently. The transition is what deleted the DB awhile back 😬

**Comment by DeeDeeG** [comment]
If GitHub had a shocked/horrified emoji reaction, this would be the time I'd press it.

Welp.
