### ISSUE TITLE
Clean up old PRs (older than 30 days)

### ISSUE THREAD

**Issue by dannypaz** [RefugeRestrooms/refugerestrooms#308]
I think it would be good to either 1. close or 2. fix and merge open PRs that are older than 30 days. 

This will: 
1. Allow us to figure out next milestones for the application
2. remove the impression of a stale project/repo

**Comment by mi-wood** [comment]
@dannypaz, I agree it'd be great if everything was current. Part of it is that @tkwidmer and I don't get the chance to dedicate the proper time to each PR to get it through and that also lends to people not following up.

I just went ahead and checked on a few of the older ones (including closing one of my own 😅 ). I've got some free time tomorrow and will follow up on some others.

I also opened up: https://github.com/RefugeRestrooms/refugerestrooms/issues/312 which might help us assign PRs quicker.

Open to some more thoughts!

**Comment by mi-wood** [comment]
Closing this as it's cleaned up to the point where people have responded recently.
