### ISSUE TITLE
rbenv issue on vagrant up

### ISSUE THREAD

**Issue by kurtcarpenter** [RefugeRestrooms/refugerestrooms#309]
On first-time start of the vagrant box, rbenv fails to install ruby 2.3.1:

```
==> default: installing rbenv...
==> default: Cloning into '.rbenv'...
==> default: Cloning into '/home/vagrant/.rbenv/plugins/ruby-build'...
==> default: install ruby 2.3.1
==> default: ruby-build: definition not found: 2.3.1
==> default: See all available versions with `rbenv install --list'.
==> default: If the version you need is missing, try upgrading ruby-build
==> default: :
==> default:   cd /home/vagrant/.rbenv/plugins/ruby-build && git pull && cd -
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by dannypaz** [comment]
@kurtcarpenter I took a look at this issue this morning and was able to find more information on this issue [here](http://stackoverflow.com/questions/29357603/ruby-build-definition-not-found-2-2-1).

It looks like the ruby-build that is being used in vagrant could/maybe/notsure is a local copy (from your local machine).

Could you post the following commands:
`ruby-build --version` and `brew update && brew upgrade ruby-build`

I will try to help you troubleshoot to get you started. Also, if you are interested, there is a slack channel for refuge that we can use, too.

**Comment by kurtcarpenter** [comment]
I don't have ruby installed on the host machine- ~~I believe this is an issue with ruby-build's version cache not being up-to-date on setup.~~ turns out this was really an issue with newlines on .ruby-version not being stripped by the setup script

On the guest machine:
```
vagrant@refugerestrooms:~$ ruby-build --version
ruby-build 20170201-12-g4e80d99

vagrant@refugerestrooms:~$ rbenv versions | grep 2.3.1
* 2.3.1 (set by /home/vagrant/.ruby-version)

```
