### ISSUE TITLE
Contributor Skill Guide

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#312]
I'm wondering if there's a good way that we could organize contributor's skill sets. Since we're a somewhat sparse community and not all of us know each other's work, it could be good for when a an issue or code review needs to be assigned. It would also be great so that new contributors could be paired for a PR and help them get better adjusted. 

Haven't thought too much about what this would look like, but came to mind today. I also think the slack gives us a good first start on this, since we can just ask around.

**Comment by tkwidmer** [comment]
I'm in favor of this.

**Comment by tkwidmer** [comment]
I think we can create a wiki page for now.

**Comment by tkwidmer** [comment]
https://github.com/RefugeRestrooms/refugerestrooms/wiki/Contributor-Skill-Guide, @mi-wood and others can update what skills they have.
