### ISSUE TITLE
Geocode (map pin) preview when submitting a new restroom

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#314]
Hi all,

It would be great to see the pin on the map before hitting submit, to avoid misplaced locations. Particularly because deleting or editing entries can't be done by a regular user right now.

I submitted a restroom and included the address copy-pasted from the place's website. This didn't geolocate properly, and ended up in the middle of the nearest town.

See:

http://www.refugerestrooms.org/restrooms/17713 (incorrect entry)

http://www.refugerestrooms.org/restrooms/17714 (correct entry)

(If someone would be kind enough to delete the incorrect entry, that would be great.)

**Comment by micahcochran** [comment]
I assume the "Contact us about this post!" link is how to get entries fixed.

**Comment by DeeDeeG** [comment]
I did report it via the "contact us" link, but it hasn't been deleted. I hope that doesn't mean there is an issue receiving comments from users. Maybe it's just that there's a backlog, or something like that. But I don't have enough information to say either way, so those are just guesses.
