### ISSUE TITLE
Test New Production

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#317]
it's been a very long time since we've deployed, but I've got the newest develop branch running with a few changes in a separate environment.

It would be great if people could try and break refuge-production.herokuapp.com. Note that this is using the prod database, so don't create any improper listings!

**Comment by tkwidmer** [comment]
Link to new production: https://refuge-production.herokuapp.com/

**Comment by tkwidmer** [comment]
When you create an issue, please attach a milestone tag 'Ceder-14 Upgrade'

**Comment by tkwidmer** [comment]
Opened #322

**Comment by DeeDeeG** [comment]
I looked for things that don't work, but I didn't see anything that wasn't in an open issue already. I ran into #322 and #295 but I'm not recalling much else being an issue.
