### ISSUE TITLE
Text Search from Home Page is Broken [Ceder-14]

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#322]
The auto complete, and search functionality seems to be broken on the ceder-14 production. This should be a simple fix. In addition the popular cities do not seem to show any results when you click on them. 

![screen shot 2017-03-27 at 11 16 46 am](https://cloud.githubusercontent.com/assets/5265597/24371176/e5245648-12de-11e7-97f9-957810b50c4f.png)
![screen shot 2017-03-27 at 11 16 33 am](https://cloud.githubusercontent.com/assets/5265597/24371369/69db9414-12df-11e7-970f-a6fa14be29d0.png)

**Comment by dannypazz** [comment]
@tkwidmer what is the URL for this test env?

**Comment by DeeDeeG** [comment]
I'm not tkwidmer, obviously, but I believe the URL is: https://refuge-staging-14.herokuapp.com/

**Comment by DeeDeeG** [comment]
Text search is working right now at https://refuge-production.herokuapp.com.

Popular cities from the homepage isn't working anywhere... [refuge-staging-14](https://refuge-staging-14.herokuapp.com), nor [refuge-production](https://refuge-production.herokuapp.com), nor [refugerestrooms.org](http://www.refugerestrooms.org).

Looks like it tries to just search for the text Seattle WA, whereas the search backend always seems to expect latitude and longitude along with whatever text. The text is cosmetic at the results page, letting users know what they typed. The lat + long is what the backend uses to make things really work.

Somehow the popular cities links are bypassing the backend, and going straight to the results page without geolocation ever being applied to the city names. Maybe Google Maps API changes caused this? (a guess.)

**Comment by mi-wood** [comment]
Thanks for the write-up @DeeDeeG. I'm wondering if the easier solution to this problem is just getting rid of popular cities? @tkwidmer  how do you feel about that? I'm not sure how useful searching all of SF or Seattle from the landing page is.

**Comment by DeeDeeG** [comment]
Just a note:

I checked out the 1.5 release tag to see how this used to work. 

It used to show you the results page with no results, for a moment, then redirect to a properly geocoded search.

**Comment by tkwidmer** [comment]
I'm ok cutting this feature

**Comment by tkwidmer** [comment]
Changing the title to refect the remaining issue, since #327 is open to remove the top cities.

**Comment by tkwidmer** [comment]
Wait. this seems to be working now on staging. http://staging.refugerestrooms.org/, I'm going to go ahead and close this. Something we've done fixed this.
