### ISSUE TITLE
Minor Vagrant issues

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#326]
Hello,

I don't know if this interests anyone, but it's been very helpful to me.

Setting up the directory structure like this lets you mess around a lot more freely with commits, adding/deleting files.

- [folder, name this whatever you want]
  - `Vagrantfile`
  - `.vagrant`
  - [refugerestrooms]
     - `project files from github`

Used to be that if you moved around too much (eg `git reset --hard [commit from the v1.5 tag]`), the hidden .vagrant folder could get lost somewhere along the way, and you wouldn't be able to run `vagrant up` anymore. (it would say "there is already a VM named refugerestrooms.") I used to lose track of my .vagrant folder and have to wait for an hour setting up vagrant all over again. Now I don't have that problem. I haven't tested this super thoroughly, but it's worked so far.

Just have to make sure to revert your refugerestrooms folder to the same commit just before every `vagrant up`, or else a server dependency might have changed.

**Comment by DeeDeeG** [comment]
Oh goodness, I hit enter too soon. I promise this makes sense.

**Comment by DeeDeeG** [comment]
You could have repos set up so that you do these steps to fetch the repos:

git clone https://github.com/RefugeRestrooms/refuge-vagrant
cd refuge-vagrant
git clone https://github.com/RefugeRestrooms/refugerestrooms

and these steps to get vagrant up:

cd ..
vagrant up

**Comment by DeeDeeG** [comment]
Setting up vagrant outside the main repo requires two changes in the Vagrantfile:

config.vm.synced_folder ".", "/vagrant/", type: "rsync"  `->`
config.vm.synced_folder "**./refugerestrooms**", "/vagrant/", type: "rsync"

and

config.vm.provision "shell", path: "setup/setup_vagrant.sh", privileged: false `->`
config.vm.provision "shell", path: "**refugerestrooms**/setup/setup_vagrant.sh", privileged: false

**Comment by mi-wood** [comment]
@DeeDeeG I'm not entirely sure what the root cause is here. The `.vagrant` file is under `.gitignore` and shouldn't change unless you manually `rm` it or something similar.

I feel like adding a layer of repositories might be slightly more confusing to setup for newcomers.

**Comment by DeeDeeG** [comment]
> I feel like adding a layer of repositories might be slightly more confusing to setup for newcomers.

Yeah, agreed. 

It's not really good as a default, kinda clunky, but it solves a problem I was having.

I don't know what causes it, but there's no proper known solution, either. 

Here is a thread about it, which says you have to keep proper track of the machine ID (stored in .vagrant directory) or the VM may be unable to be started:

https://github.com/mitchellh/vagrant/issues/2969#issuecomment-50702493

**Comment by DeeDeeG** [comment]
Not to clog up the issues page, I found another Vagrant issue.

Vagrant 1.9.3 (latest version) errors out during "vagrant up" on Windows. 

This is addressed at Vagrant/master on GitHub. There is also a workaround described here, while Windows users wait for the next release of Vagrant to come out:  https://github.com/mitchellh/vagrant/issues/8395#issuecomment-288379271

**Comment by DeeDeeG** [comment]
Closing this, since neither of these is an ongoing problem as far as I can tell. (Also: they've only affected me so far, and I know how to deal with them!)
