### ISSUE TITLE
Interested in making a "Maintainers'/Newcomers' Manual" for working on the Refuge Restrooms site

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#334]
Hi all,

I have this idea in my head about a great resource for newcomers, with some advanced tips/tricks thrown in.

This could take the form of a "GitHub Wiki", or could just be a variety of text files in the repo.

My goals for the content of this guide would be to include brief primers on core technologies we are using

- Ruby and Rails
- HAML
    - Mostly just link to this: http://haml.info/tutorial.html
- SASS
- Vagrant
- Cucumber
- Google Maps API

And also some relevent tips and tricks such as 

- linking to the "advanced merge" guide at the official git documentation: https://git-scm.com/book/tr/v2/Git-Tools-Advanced-Merging
- "Unit Tests, How Do?"
- troubleshooting with Vagrant (listing all the minor snags you might run into with Vagrant and the relevent fixes.) As in #326.
- My build failed, How do I know what caused it?

This would ease in folks with a skillset big enough to contribute work, but who nonetheless have difficulty testing their changes, or making their changes compatible and mergeable, due to a high technical learning curve somehwere else in the project (usually somewhere outside their wheelhouse, eg I have trouble with javascript, and am unfamiliar with ruby and unit tests)... And the guide could help people brush up on skills or troubleshoot when they've already started contributing and run into a snag.

Thoughts?

**Comment by mi-wood** [comment]
All for this! Happy to work with you on this where I can help. Honestly, even I'd benefit quite a bit from this 😂 

I'd like if the `README.md` was a little bit lighter too (for finding a quick description and index). I'm always a big fan of hierarchical index structure where needing help outside of the project itself (ex. git tips) would then be linked from corresponding pages (contributing guide pulling down git repo section or something).

Seems strongly linked to (if not duplicate) of https://github.com/RefugeRestrooms/refugerestrooms/issues/321

**Comment by DeeDeeG** [comment]
>Seems strongly linked to (if not duplicate) of #321

Yep. Didn't want to presume this idea was the way to do #321, without anyone else's input, since I just made it up myself and it's kind of a project-wide thing, but it's pretty much in response to that. Glad to hear you're for it!

I am leaning toward a wiki for my own sake, since I'm familiar with editing Wikipedia, but my gut also tells me that `xyz.md` is more accessible to newcomers and possibly more likely to be read...

Picking one of these soon/before we have a lot of "orphaned pages" written and no "root" that they all branch from would be a plus. (Are GitHub Wikis styled with Markdown? If they are I guess it doesn't matter whether this starts in `xyz.md` pages or wiki; switching would be easy.)

Related: I just noticed I have access to edit the github.com/refugerestrooms/refugerestrooms Wiki, so probably going to start there. I don't want to evict the existing pages or anything, so I imagine there should be a "Maintainer's Manual" (or whatever name) page as the main root for these pages we are hypothetically going to write for the guide.

>I'm always a big fan of hierarchical index structure

So, like this, I imagine?: https://en.wikipedia.org/wiki/Tree_structure All I really care about there, as in the only strict "rule" I can think of, is that everything can be gotten to from "page 1" with a few clicks. ("Page zero" is probably README.md for our purposes since, that's what our collaborators all read and have easy access to).

I suggest pages get written in some mixed order between what we feel ready to write, that being one source of pages to do first, and later as it shapes up as a resource, write what is most-needed or knocks away the biggest problems for a contributor. That's implied by the initial post for this issue, but just writing that down to explicitly share my thoughts on these things.

I honestly think I'm just going to get started and we'll move from there. As they say on Wikipedia: "[Be Bold](https://en.wikipedia.org/wiki/Wikipedia:Be_bold)"

**Comment by DeeDeeG** [comment]
I'm going with a very informal, but hopefully direct and to-the-point style. I hope this will be engaging and pleasant to deal with, and also helpful.

Any comments on this, or any change of direction on that, I am open to it.

**Comment by mi-wood** [comment]
@DeeDeeG I'd definitely say just have at it and I'm happy to review and update it more. Thanks!

**Comment by DeeDeeG** [comment]
I did everything on my list in post 1, Except: Cucumber (couldn't find any sources to learn from yet.) and Rails.

Rails would be great to document, so I might look into that. Anyone with Rails expertise would be quite welcome to go and do it, though, obviously. 😁

**Comment by DeeDeeG** [comment]
Closing because the guide exists now!
