### ISSUE TITLE
Avoid installing (i.e. compiling) ruby from source during vagrant up?

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#336]
#Hi all,

One of the biggest time sinks right now when running vagrant up is compiling ruby from source. I wonder if we could compile once, host the compiled version in, say https://github.com/refugerestrooms/third-party-ruby or something like that, then download and install the binary from there, instead of compiling every time we make a new vm?

Right now vagrant up runs somehwere near and hour to an an hour and a half for me. I think it would be super convenient and great if we could bring that down to a more manageable, quicker provision. More convenient testing = more testing and happier devs?

**Comment by DeeDeeG** [comment]
#### Research links

How to make a package as a .deb https://ubuntuforums.org/showthread.php?t=910717

**Comment by mi-wood** [comment]
Another way to do this might be creating our own vagrant base box that already has ruby and the other dependencies set up. We could host this somewhere. Maybe there's something free, or s3 will cost practically nothing for this. Then people just have to download that box and it's all set up. The setup script is idempotent, so it can always be run for minor updates after that.

**Comment by DeeDeeG** [comment]
>Idempotent

I learned a new vocab word today!

That all sounds good to me. Just popping in again to say that Nokogiri is the other large-ish consumer of time during vagrant up, as it too compiles from source. Although I see on its website that is by design.

>Another way to do this might be creating our own vagrant base box

Wow, that would be amazing.

I found a link to a lengthy but relatively easy-looking tutorial for creating the box: https://github.com/hollodotme/Helpers/blob/master/Tutorials/vagrant/self-hosted-vagrant-boxes-with-versioning.md

I assume this isn't strictly the only way to do it, but it answers most of the unknowns from my perspective.

Also, if downloading a box from some third party seems sketchy (it does to me), this tutorial does the first steps starting from scratch, with Ubuntu downloaded from Ubuntu.com: https://www.sitepoint.com/create-share-vagrant-base-box/

**Comment by DeeDeeG** [comment]
If we would be comfortable moving away from rbenv, I would be interested in moving forward with the .deb packaging of ruby. That seems less daunting to me than the vagrant box solution.

The Ubuntu bug tracker thingy, "Launchpad.net," has a .deb package hosting solution, for free, baked into it, so we wouldn't have to worry about hosting costs/logistics. 

For integrating it with our `vagrant up` setup process: I could upload the .deb at launchpad, as mentioned above. We could then have the script download the .deb from launchpad.net, with `wget`, then install it with `apt install ./[package_name].deb`

Regarding the vagrant box route: there are a couple of kind-of-hacky ways to do this, other than paying Amazon to host the file. One of us could set up a home server and serve the files from there (probably a bad idea). We could throw it on a dropbox account or similar and download from there (maybe against terms of service, would have to double check). Kind of sneaky, and not sure if against the terms of service, we could host the boxes on GitHub, if possible (may run into some sort of filesize limit).

**Comment by DeeDeeG** [comment]
I've been working on this. I made the box, but adding it manually, it or having it hosted so it will download automatically, are still a bit complicated.

Here's a link to grab the box file I made: https://www.dropbox.com/s/pc7wi24swy5iql2/refugerestrooms-box-test-1.0.box?dl=0

You can add it with 
`vagrant box add file:///[path-to-box-file-wherever-you-downloaded-it-to] --name [some-name]`,
 and then change the Vagrantfile to have the line `config.vm.box = [some-name]` (must be the same name as you used in `vagrant box add`).

to preserve your existing `refugerestrooms` vagrant box, edit your Vagrantfile to have `BOXNAME = "refugerestrooms-box-testing"` or whatever BOXNAME value other than "refugerestrooms"

So, I have a box file, but it's tricky setting it up to be downloaded automatically. It involves making/hosting a "catalog", (a small json file) and specifying its URL in the Vagrantfile, and then properly hosting the catalog and the box file on a file server somewhere on the internet. I have the box hosted on Dropbox, and I put the catalog on GitHub, but Vagrant gets tripped up on both of these. 

(GitHub sends the catalog in a weird way that Vagrant can't figure out is a json file... and the Dropbox URLs all either have redirects that Vagrant can't figure out how to navigate, or session/authentication mechanisms that end up blocking Vagrant. Google Drive is the same about this as Dropbox is.)

So we would need to probably get something like AWS to make it work, or have one of us host our own server.

**Comment by DeeDeeG** [comment]
Here's how I've been making the .box file:

Clone the repository: 
 - `git clone https://github.com/RefugeRestrooms/refugerestrooms`

Get the vm provisioned:
 - `cd refugerestrooms`
 - `vagrant up`
 
SSH into the vagrant box: `vagrant ssh`

Delete unnecessary software (I found that these things take up a lot of space): 

 - `sudo apt purge juju juju-core`
 - `sudo apt purge libicu52`
 - `sudo apt purge libllvm3.4`
 - `sudo apt purge libsane libsane-common`
 - `sudo apt purge fonts-dejavu-core fonts-ubuntu-font-family-console`

(Optional: Use ncdu to find software packages to remove:)
 - `sudo apt install ncdu`
 - `cd /`
 - `ncdu`
 - *find something taking up space using ncdu*
 - *press* `q` *to exit ncdu*
 - *remove stuff with* `sudo apt remove [package]` *or with* `rm -rf [/path/to/thing]`

(And when you're done with ncdu, remove it:)
 - `sudo apt purge ncdu`


Clear the cache for the software/package manager (APT), (takes up lots of space):

 - `sudo apt-get autoremove --purge`
 - `sudo apt-get clean`

Make sure users will be able to SSH into your vagrant box (reset the SSH key to the default one):

 - `cd ~`
 - `rm .ssh/authorized_keys`
 - `wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -O .ssh/authorized_keys`
 - `chmod 0600 .ssh/authorized_keys`
 - `chown -R vagrant .ssh`

Clear a lot of space, by making every empty bit of the virtual hard-drive a zero (data that's all zeroes in a row can be compressed to almost nothing, and this saves a ton of filesize, since the .box file contains a compressed file system):

 - `sudo dd if=/dev/zero of=/EMPTY bs=1M`
*wait a while*
 - `sudo rm -f /EMPTY`

Turn off and exit the VM:
 - `sudo shutdown -h now`

Make the .box file from the machine we were just tidying up:

 - `vagrant package --base refugerestrooms --output refugerestrooms.box`

(Hint for how to format this command:)

 - `vagrant package --base` <VM_Name_exactly_as_shown_in_Virtualbox_GUI> `--output` <ANY_FILENAME.box>

**Comment by DeeDeeG** [comment]
Hard to believe this is so fast and easy with RVM/Docker! Thanks! 

(Haven't tried Docker yet, but looking forward to it! I saw in the Travis log that it just downloads a binary, pre-built ruby!)
