### ISSUE TITLE
Caching issue when accessing the new refugerestrooms.org

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#343]
Hi all,

Here is what's up with this:

- Trying to visit the site with "www" in the URL ("http://www.refugerestrooms.org") gave me an "internal server error". Visiting "http://refugerestrooms.org" *without www in the URL*, worked fine.
    - The problem went away after I cleared my browser cache, so this will be solved for all users automatically, after their caches expire. Users can clear cache to workaround the issue.
        - [how to clear cache for all browsers](http://www.pcmag.com/article2/0,2817,2480401,00.asp)

I'm not familiar with how this is addressed, but I thought I'd report it anyway.

**Comment by mi-wood** [comment]
I had to clear my cache and it worked. Not sure what the best way to handle that for everyone else is though.

**Comment by DeeDeeG** [comment]
In my experience, sites much bigger than us have dealt with cache issues, by finding a way to message to users that there is a fix, albeit via rather obscure "help/support" pages... And then other than that just wait it out. :| we could let our Twitter followers know. But... That involves broadcasting to the world a technical glitch many may not be aware of, so there's the plus side and the down side to that. 

I do want to point out that this affects us developers consistently, since we visit the site very frequently on the same machines, whereas other folks may not visit our site consistently every day and might be less likely to see this issue. That said, ironically, people who have a consistent pattern of using our site are the most affected, including some who may rely on us more than average. 

While writing this, I thought of something. If we have any control knobs where we can *disable* caching for our site for say, 24 hours, 48 hours, we will take a performance hit for visitors getting more than one page from our server, but I believe their browsers will have to download everything fresh, and hopefully there would be no conflicts then.

**Comment by DeeDeeG** [comment]
From my previous comment, I looked at how to disable caching.

Here's a config file where we set up (explicitly disable) caching when developing:

https://github.com/RefugeRestrooms/refugerestrooms/blob/bcdcb275bcb91191d1f1a6af18991dbf4fb20f30/config/environments/development.rb#L24 (disable caching)

https://github.com/RefugeRestrooms/refugerestrooms/blob/bcdcb275bcb91191d1f1a6af18991dbf4fb20f30/config/environments/development.rb#L26 (type of cache is "null" ?)

(There's parts of that config where caching is flipped on if we make a file called tmp/caching-dev.txt, but I'm ignoring that part and focusing on where caching is disabled.)

Here are two places of our production config file where we deal with caching, with settings different to the aforementioned part of the development config file:

https://github.com/RefugeRestrooms/refugerestrooms/blob/bcdcb275bcb91191d1f1a6af18991dbf4fb20f30/config/environments/production.rb#L15 (enable caching)

https://github.com/RefugeRestrooms/refugerestrooms/blob/bcdcb275bcb91191d1f1a6af18991dbf4fb20f30/config/environments/production.rb#L53 (commented out: type of cache is "memory only")

We could basically copy the development way of doing caching into our production config file.

If we wanted to do this, I think we should set up a "hotfix" branch or similar here on github, deploy that for a day or two, up to about a week, then go back to deploying the "develop" branch again.

I'm not sure if it would solve the problem at hand, if we **did** enable caching, but only allowed caching in memory, because I think that style of cache gets deleted every time the user closes their browser. But the intended benefit of using memory caching would be, the performance hit we would take by serving full content to repeat visitors should be reduced some.

**Comment by DeeDeeG** [comment]
Whoops, I think what I was looking for was HTTP Cache headers.

Such as:

```
    config.public_file_server.headers = {
      'Cache-Control' => 'public, max-age=172800'
    }
```

From: [config/environments/development.rb](https://github.com/RefugeRestrooms/refugerestrooms/blob/bcdcb275bcb91191d1f1a6af18991dbf4fb20f30/config/environments/development.rb#L21)

We should just add something like that to our production config. If we want to deploy a hotfix, to this caching issue, I mean.

**Comment by DeeDeeG** [comment]
I think the caching issue is resolved formost users by now. In any case this one fixes itself over time! Closed.
