### ISSUE TITLE
HTTPS is 99% working, except the certificate points to *.herokuapp.com, instead of Refugerestrooms.org

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#345]
We have a working https connection, sort of: If you click through your browser's "this connection is not secure" warning, https://www.refugerestrooms.org will deliver you encrypted assets.

The problem is, our certificate is set up to work on herokuapp.com, so we need that edited to work on Refugerestrooms.org

I think this guide from Heroku is the most relevent support doc for this problem (no experience with it myself, but it looks like it coukd take under half an hour to address?): https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by stardust66** [comment]
This is important because I don't think location services work through HTTP, at least that's what it said in the Google Chrome js console. The HTTP site should redirect to the HTTPS site.

**Comment by mi-wood** [comment]
I originally tried to set up that with heroku's wildcard cert which causes issues with "www". I'll take a peak at this once I get a sec. We have some funds we could use if it's easy to just pay heroku to manage it for us.

**Comment by mi-wood** [comment]
Linked to: https://github.com/RefugeRestrooms/refugerestrooms/issues/83

**Comment by mi-wood** [comment]
Ah, looks like it's changed a bit. If we just upgrade our dynos to hobby ($7/month) we can enable ssl with a single command. I think that's worth it. @tkwidmer sound good?

**Comment by Hkly** [comment]
As an aside, is there a way for folks to contribute financially to help offset the costs of stuff like this?

**Comment by mi-wood** [comment]
@Hkly We've got funds from Fund Club to pay for this :)

**Comment by DeeDeeG** [comment]
@Hkly There's also the Patreon (which was mentioned on Twitter once, I think).

https://www.patreon.com/refugerestrooms

**Comment by mi-wood** [comment]
@DeeDeeG Hi!!

**Comment by DeeDeeG** [comment]
Hi, I'm still around, just been busy! Hoping to keep contributing as I can/when I've got more free time!

**Comment by mi-wood** [comment]
No worries! I was just excited to see your name :)
