### ISSUE TITLE
Cleanup the map view's marker box

### ISSUE THREAD

**Issue by kurtcarpenter** [RefugeRestrooms/refugerestrooms#352]
Currently, the box looks out of place (solid white background, 1px solid black border, no padding), and the filter icons are vertical and spill out of the box. It would be nice if it didn't block out the map (i.e. partially transparent), had padding, and filters icons were horizontal (maybe with tooltips?)

<img width="303" alt="map-details" src="https://user-images.githubusercontent.com/9683513/27108068-645cafa6-5069-11e7-96dd-8bcbbadd562d.PNG">

**Comment by Hkly** [comment]
And I way to close the modal could be helpful too! 

I think I would like to tackle this one.
