### ISSUE TITLE
Preview does not load with "Guess current location"

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#366]
The preview works great if I fill in an address, but "Guess current location" causes the button to not work. I'll take a quick peak as to why. Still going to deploy to master, since this is a minor issue

**Comment by mi-wood** [comment]
@stardust66 @Hkly fyi

**Comment by stardust66** [comment]
Oops I found the problem. I forgot to put `@_map.classList.remove("hidden")` in the `updateMap` function. Instead I put it in the call back for when the preview button is clicked, so clicking the guess button doesn't unhide the map. I'll move it.
