### ISSUE TITLE
https://refugerestrooms.org showing wrong cert

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#368]
Not really sure why it's showing this...  Has been confirmed on other people's computers and safari/chrome/firefox

![screen shot 2017-08-19 at 11 44 28 am](https://user-images.githubusercontent.com/3472115/29489348-e5116760-84d3-11e7-8a62-493cb16a5b51.png)

**Comment by DeeDeeG** [comment]
For what it's worth, here is the main support article for automatic SSL setup on Heroku:
https://devcenter.heroku.com/articles/automated-certificate-management

from the [Troubleshooting](https://devcenter.heroku.com/articles/automated-certificate-management#troubleshooting) section, some setups won't work: 

> ## Known limitations
> 
>  - ACM does not support applications that have over 100 custom domains.
>  - ACM does not support applications that have wildcard custom domains.
>  - ACM does not support the SSL Endpoint add-on.
>  - ACM is currently available for apps on the Common Runtime only. It is not yet available in Private Spaces.
>  - ACM is not available if your app is behind a CDN such as Cloudflare or Fastly.
>

I wonder if any of those apply to us?

(If they do, then we can't use Automatic Cert Management and we have to upload our own certificate manually. Intstructions for that are here: https://devcenter.heroku.com/articles/ssl)

**Comment by mi-wood** [comment]
I think I fixed this. There was a lingering A-record pointing to a heroku IP. Deleted this and I think we're good.
