### ISSUE TITLE
Label search buttons for VoiceOver

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#378]
@DeeDeeG : 

> I think we need some sort of indication of what the search bar buttons do, because right now VoiceOver just reads them aloud as "button". There's two of them (the "magnifying glass", and the "location arrow".) I guess "search", and "search by my location" would do.

**Comment by babadabeer** [comment]
As far as voice over is concerned, I found samples  a few days ago and they keep appearing on audio video portals like http://hindi.media so references can be taken and if possible research over the Web itself can be helpful.

However, there are some soft tools offered by high tech portals as YouTube itself offers video audio editing to its creators.
