### ISSUE TITLE
Can't follow footer icon links with VoiceOver on outdated mobile Safari

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#390]
This issue is similar to #384. However, unlike the icon in #384, the footer links are focusable, and can be "tapped," but surprisingly nothing happens when the links are tapped using VoiceOver on mobile Safari.

I suspect this might be limited to old iOS versions from before iOS 10, like #384 is, but haven't tested it widely enough to determine that. (Outside of screen-readers, the links "just work" like they're supposed to. It's just a matter of which screen readers have issues with these links.)

Not sure if this is able to be fixed in the same way as in #389.

**Comment by DeeDeeG** [comment]
The footer links do work on an iPhone with iOS 11.2.5 (Safari 604.1).

This is probably an "older iOS" only bug.

**Comment by tkwidmer** [comment]
Closing this as not a priority since its an older IOS bug
