### ISSUE TITLE
Add a Link to Patreon

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#397]
We have a Patreon, but we don't link to it anywhere from the site. We should fix that. 
This is a perfect entry level item for somebody to take on.

https://www.patreon.com/refugerestrooms

**Comment by KurtPrice** [comment]
Where would we like to place it? In its own page or in the footer?

**Comment by tkwidmer** [comment]
I think adding a link in the footer is great. 
I also think one option is to put it on the home page in a more high profile location. 

I'm attaching a mockup with button placement, and with a button that could easily be used. 

![patreon mockup](https://user-images.githubusercontent.com/5265597/34220236-c4b95aae-e568-11e7-88ca-cb2a89a0698c.png)
![become_a_patron_button-1](https://user-images.githubusercontent.com/5265597/34220239-c74d8100-e568-11e7-998d-4672e59f4659.png)

**Comment by KurtPrice** [comment]
Do we have documentation somewhere to set up a testbed for the site under development?

**Comment by tkwidmer** [comment]
@KurtPrice Almost everything you should need for that is here: https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/CONTRIBUTING.md we use vagrant to spin up a virtual machine for development. It 'should' be pretty seamless.

**Comment by KurtPrice** [comment]
Thanks! I'll set that up so that I can make sure this looks decent when I am finished.

**Comment by tkwidmer** [comment]
I also deployed your branch here: https://refuge-staging-14-pr-398.herokuapp.com/, when you update your branch I can update the deploy.

**Comment by KurtPrice** [comment]
Thank you. I have made some adjustments and made sure that I actually added the image this time. I appreciate the staging site for my debugging. I am trying to set up vagrant now, and I understand why it 'should' be seamless haha. Thanks for the help.
The latest changes should be pushed now.
