### ISSUE TITLE
Header Brand Text is misaligned

### ISSUE THREAD

**Issue by tkwidmer** [RefugeRestrooms/refugerestrooms#400]
![header brand text is misaligned](https://user-images.githubusercontent.com/5265597/34220445-8fe044ea-e569-11e7-91db-55ac97b9f91e.png)

See Above Screenshot. Readability isn't great. Should be vertically aligned with the logo.

**Comment by DeeDeeG** [comment]
Hi, I think this is fixed in #386 but just not deployed yet.

Should be good once the release discussed in #402 goes live.

**Comment by tkwidmer** [comment]
oh word. Marked as a duplicate.
