### ISSUE TITLE
Vagrant up timeout

### ISSUE THREAD

**Issue by padalah** [RefugeRestrooms/refugerestrooms#411]
I am newcomer to OSS and I really want to contribute this project. When I run the command "vagrant up", I keep getting a time-out error.

**Comment by mi-wood** [comment]
Hi @padalah and welcome! Could you please past your error and let us know what operating system you're using?

**Comment by DeeDeeG** [comment]
Hi @padalah

If the error looks something like this: 

```
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
```

That is normal. You only need to wait a minute or two, and it will connect successfully.

Then you should see something like this:

```
==> default: Machine booted and ready!
```

I also found some threads on stackoverflow.com where people discussed similar-sounding issues:
 - https://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying
 - https://stackoverflow.com/questions/23690124/vagrant-up-timeout

I hope one of those links can help.

(And to second @mi-wood, welcome!)

(Also to second @mi-wood, we would possibly be able to help better if you can copy and paste the error you are seeing. Good luck!)

**Comment by padalah** [comment]
My operating system is Windows 10. Here is the error I am encountering:
<img width="454" alt="refrest1" src="https://user-images.githubusercontent.com/19918773/34707287-88aa8c6e-f4c1-11e7-9ca0-043664c631cc.PNG">
<img width="381" alt="refrest2" src="https://user-images.githubusercontent.com/19918773/34707290-8e81f690-f4c1-11e7-83da-b285621e8a38.PNG">

**Comment by DeeDeeG** [comment]
I would run `vagrant destroy`, delete any `.vagrant` folder within your RefugeRestrooms folder, then try `vagrant up` again.

I think there was just a mis-configuration when bringing up the virtual machine the first time, and starting over might clear it up.

If that still doesn't work, maybe your version of Vagrant or VirtualBox is out-of-date?

I also found a blog post about dealing with this problem, if none of that helps: https://tomjn.com/2016/08/03/vagrant-provision-timeouts/
