### ISSUE TITLE
IRC => Slack in docs

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#416]
We should update the docs to have people request slack invites, since we don't user IRC anymore

**Comment by DeeDeeG** [comment]
A [search](https://github.com/RefugeRestrooms/refugerestrooms/search?utf8=%E2%9C%93&q=IRC) of the repo's code turns up two mentions of IRC:
 - [`travis.yml`](https://github.com/RefugeRestrooms/refugerestrooms/blob/641357535b01c9ed8454392e2e26520dd0a5a93a/.travis.yml)
- [`README.md`](https://github.com/RefugeRestrooms/refugerestrooms/blob/2598fa29bd068061d906661a568ae7e0d28b0060/README.md)
The Travis config file apparently notifies the IRC channel of Travis' activities. Not sure if want to get rid of that or not. (I've never personally used it so I have no investment there either way.)

Readme.md just says

```
## IRC

Server: irc.freenode.com
Channel: #refugerestrooms
```
---

Could probably be replaced with
```
## Slack

Request an invite to RefugeLGBT's Slack page here: [#286](https://github.com/RefugeRestrooms/refugerestrooms/issues/286)
```

Or...
```
## Slack

Email Teagan for an invite to our Slack: [email@example.com](mailto:email@example.com)
```
Or... etc.

I'm not sure who they should contact, or if they should open a new issue, etc. but it seems like it would entail a simple update to the `readme`.

**Comment by DeeDeeG** [comment]
For what it's worth, I looked into just linking people to `refugelgbt.slack.com`, thinking there would be a "request invite" link, but there isn't one. It simply says to contact the administrators:

![refugelgbt_slack-not-signed-in-with-arrow_scaled-down](https://user-images.githubusercontent.com/20157115/34689777-b72902a6-f484-11e7-8823-edb9d9f5e834.png)
