### ISSUE TITLE
Hindi Translation

### ISSUE THREAD

**Issue by ashishwadekar** [RefugeRestrooms/refugerestrooms#431]
Hi there,

I am willing to add Hindi translation for the website based on @DeeDeeG & @Intimaria working for Spanish translation.

I am more than happy to do my little part for the community in India & folks who will be using it while travelling.

Cheers,
Ashish

**Comment by DeeDeeG** [comment]
Hi @ashishwadekar, thanks again for volunteering to do this.

I think the English translation files are finally sorted out, and they are stable for now.

By the way, the hindi locale is abbreviated `hi`, so you could make a `hi` folder in this repo's `locales` directory and copy the English `filename.en.yml` files in there if you want to get started. 

(the full path for the folder would be `config/locales/hi`)

Then for each file,
- rename from `filename.en.yml` to `filename.hi.yml`.
- And change the top line of each file from "`en:`" -> "`hi:`".

We are here to help as always.

**Comment by ashishwadekar** [comment]
@DeeDeeG Thanks for the heads up, information & help.
