### ISSUE TITLE
Weird nesting for locale folder? 

### ISSUE THREAD

**Issue by Intimaria** [RefugeRestrooms/refugerestrooms#437]
Hi, I noticed this just now as I was looking through the code, 
the en folder is oddly nested withing the locales folder (image attached).
I did notice it in  the Spanish-1 branch when I was looking to merge the reviewed translations but I thought it was an error. It's a minor issue, but wondering is this an error or is it the correct setup?

![weirdlocalefolder](https://user-images.githubusercontent.com/4869398/35537804-5cc8e888-052a-11e8-99fa-3fbf43e406f1.png)

**Comment by mi-wood** [comment]
@Intimaria are you referring to the fact that the `en` appears on this page rather then once `locales` is clicked? This is the default behavior for GitHub when only one subfolder exists

**Comment by DeeDeeG** [comment]
Yes, GitHub is just trying to save you the effort of clicking into `locales` only to find there is nothing there but another folder, `en`.

If you imagine this long set of folders with nothing in them but other folders:

`Folder` -> `subfolder-1` -> `subfolder2` -> `subfolder3` -> `subfolder4` / `some file.txt`

GitHub would just show this as `Folder/subfolder1/subfolder2/subfolder3/subfolder4`, and when you clicked on it you could view `some file.txt` without having to click 5 times to get there.

**Comment by Intimaria** [comment]
Oops, my bad. Sorry. I think I’m a bit burnt out! I’ll close this now.
