### ISSUE TITLE
Analyze Thread Safety

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#445]
https://github.com/RefugeRestrooms/refugerestrooms/pull/442 brought up whether our app is thread safe or not. If for whatever reason we need to use multiple threads for the app, we should evaluate if we can

I found this article, which seems to be a pretty good start:
https://bearmetal.eu/theden/how-do-i-know-whether-my-rails-app-is-thread-safe-or-not/

**Comment by vinzruzell** [comment]
Requesting for filipino translation

**Comment by mi-wood** [comment]
I'm going to close this until we need multi-threading, because I don't think that will be for a long time and this will just cloud the issue list.
