### ISSUE TITLE
Convert CoffeeScript to JS

### ISSUE THREAD

**Issue by mi-wood** [RefugeRestrooms/refugerestrooms#456]
It's probably time we solidify around just using JS. CoffeeScript is not a common language to use and it doesn't make sense to have two scripting languages at once (the map views use js for example)

I found https://decaffeinate-project.org/, which probably get's a lot of the easy stuff done, but will require finding what bugs that produces and patching them.

**Comment by stardust66** [comment]
I just tried out decaffeinate, and it works, except that it uses ES6, which Phantomjs and older browsers don't support. It's in the "assumptions" section of their [conversion guide](https://github.com/decaffeinate/decaffeinate/blob/master/docs/conversion-guide.md).

https://github.com/ariya/phantomjs/issues/15287
> Introducing ECMA will require nearly-complete rewrite and - keeping in m8ind I seem to be the only active dev of PJS now - will need to wait till other - more urgent - issues are solved.

What do you think about adding Babel so we can use decaffeinate and write more modern javascript while still having tests pass?

**Comment by mi-wood** [comment]
@stardust66 thanks for getting started on this! I would say go ahead and use babel if that's what you think is best. going to defer to your judgement since you've been working with the js the most

**Comment by tkwidmer** [comment]
i'm in favor of introducing ES6. This allows us to maybe eventually decouple the two.
