### ISSUE TITLE
CI is failing on certain tests that use Poltergeist

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms#469]
Starting this issue to track efforts to solve this problem.

Routes to solve the problem:

- Tweak tons of small things, see if any of them fix the failing tests

- Switch away from Poltergeist for another headless browser

Switching away from Poltergeist is supposed to be pretty easy, and should not require re-writing any tests. Capybara abstracts away all browser capabilities, and since we use Capybara, we should be able to easily swap out any headless browser compatible with Capybara.

Past attempts to fix this:

- https://github.com/RefugeRestrooms/refugerestrooms/pull/460
- https://github.com/RefugeRestrooms/refugerestrooms/pull/461
- https://github.com/RefugeRestrooms/refugerestrooms/pull/462
- https://github.com/RefugeRestrooms/refugerestrooms/pull/463
- https://github.com/RefugeRestrooms/refugerestrooms/pull/464
- [remove-poltergeist_debug](https://github.com/RefugeRestrooms/refugerestrooms/commits/remove-poltergeist_debug)

**Comment by DeeDeeG** [comment]
Filed an issue upstream at the Poltergeist repo in case this might be a genuine bug in Poltergeist: https://github.com/teampoltergeist/poltergeist/issues/917

**Comment by DeeDeeG** [comment]
[Comment](https://github.com/teampoltergeist/poltergeist/issues/917#issuecomment-368621291) in the upstream issue:

---

If you run it with `selenium` as the driver you can see the same things happens, and see the browser is waiting for a request from `csi.gstatic.com`. The issue appears to be that the map display hangs requesting resources to populate the iframe it adds to the page. You can get the tests to run (some fail) by configuring the driver to ignore JS errors and blacklist `googleapis.com` -

```
  Capybara::Poltergeist::Driver.new(app,
    :js_errors => false,
    url_blacklist: ['googleapis.com']
  )
```

This means you won't actually be able to test anything relating to the map, but I'm not sure what else can be done if the map display just hangs.

**Comment by DeeDeeG** [comment]
So, this porbably isn't a Poltergeist or PhantomJS bug; it happens even with Selenium, which I think uses Firefox. But in any case, Selenium has nothing to do with Poltergeist.

This looks like a problem on the Maps API side. Maybe our maps API quota is being maxed out? Or some other issue with GMaps?

**Comment by mi-wood** [comment]
Thanks @DeeDeeG that's a huge help! I think I'm going to disable those tests for now in favor of having all tests run, and we can create an issue about map tests.

**Comment by mi-wood** [comment]
Actually, this is hanging in production too, so I'll try to figure out what's up.

**Comment by mi-wood** [comment]
This is fixed here: https://github.com/RefugeRestrooms/refugerestrooms/pull/457 

Just stopped using the experimental version of the maps API

**Comment by mi-wood** [comment]
Fix is now deployed
