### ISSUE TITLE
Cannot switch back to List View in web app

### ISSUE THREAD

**Issue by kurtcarpenter** [RefugeRestrooms/refugerestrooms#478]
- Search for any location (e.g. Current Location)
- Click Map View (map gets rendered)
- Click List View

Observe that Map is still present, although the toggle button has been toggled. Repeated clicks toggle the button, but do not change to the List. No browser console errors.

**Comment by stardust66** [comment]
I think this was fixed by #471 but it hasn't been deployed to Heroku yet.

**Comment by DeeDeeG** [comment]
@stardust66 agreed.

This looks fixed now that the most recent commits are live.

Thank you @tkwidmer for deploying!
