### ISSUE TITLE
Filter buttons (ADA/inclusive) do not apply to Map View

### ISSUE THREAD

**Issue by kurtcarpenter** [RefugeRestrooms/refugerestrooms#479]
- Search a location, e.g. https://www.refugerestrooms.org/restrooms?utf8=%E2%9C%93&lat=37.7749295&long=-122.41941550000001&search=San+Francisco
- Enable/disable some filters and notice the List removes some items
- Toggle to Map View
- Enable some filters and notice the Map always shows all items, even though they do not match filters

Given some of the issues present in filtering (see #226), might be worth it to change the filtering approach not to require page reload

**Comment by Brodan** [comment]
I think I'm gonna take a crack at this one!

**Comment by GPrimola** [comment]
@DeeDeeG this is very related to the one I just did. Can I take this one too? I think it's a very low hanging fruit after #638

**Comment by DeeDeeG** [comment]
Yep, that sounds like good idea. Go for it! Thanks.
