### ISSUE TITLE
List View has text overlap on small screens

### ISSUE THREAD

**Issue by kurtcarpenter** [RefugeRestrooms/refugerestrooms#480]
We should probably make the list responsive - maybe on small widths stack the elements vertically to prevent overflow?

<img width="128" alt="screen shot 2018-05-16 at 22 53 58" src="https://user-images.githubusercontent.com/9683513/40159144-b1928a0a-595c-11e8-8028-fc86e0784160.png">

**Comment by tylerbmcsilva** [comment]
Hello! Can I give this a shot? 😄

**Comment by DeeDeeG** [comment]
Hi @tylerbmcsilva,

Yeah, go for it!

(sorry I didn't reply sooner, my email inbox fills up a little too quickly sometimes!)
