### ISSUE TITLE
Exclude third party files from code climate

### ISSUE THREAD

**Issue by stardust66** [RefugeRestrooms/refugerestrooms#492]
Most of the Code Climate issues are actually in third party libraries. We should exclude the `public/api/docs/lib` directory in the Code Climate settings.

https://docs.codeclimate.com/docs/configuring-your-analysis#section-exclude-patterns

**Comment by tkwidmer** [comment]
Done as of Monday, September 24th.

**Comment by DeeDeeG** [comment]
As @tkwidmer mentioned in Slack, we might want to also consider installing swagger-ui as a proper node package.

Our `public/api` directory is mostly (entirely?) a copy of the `swagger-ui` project from the 2.0 series: https://github.com/swagger-api/swagger-ui/tree/2.x/dist

I suspect we could install (the 2.0 version?) of the nodejs package and then update as needed.
