### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by MauroCoppola** [RefugeRestrooms/refugerestrooms#517]
## Scope / difficulty

Translation will be added in a dedicated subfolder in [config/locales](https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales)

## Impact

Improved internationalisation.

## Rationale

Let the project be understandable even for italian people who don't know english language or any other Language currently available

## Proposal

Add the italian translation

## How to actually do this:

Translate all files inside [config/locales/en](https://github.com/RefugeRestrooms/refugerestrooms/tree/develop/config/locales/en)

**Comment by DeeDeeG** [comment]
Hi @MauroCoppola,

An Italian translation would be great!

We have some instructions for translating Refuge Restrooms here if anyone wants to take a look: https://github.com/RefugeRestrooms/refugerestrooms/wiki/How-do-I-translate-Refuge-Restrooms.org%3F

**Comment by DeeDeeG** [comment]
By the way, if anyone wants to get started on this: The Italian locale is abbreviated `it`, so one could make an `it` folder in this repo's `locales` directory and copy the English `filename.en.yml` files in there.

(the full path for the folder would be `config/locales/it`)

Then for each file,
- rename from `filename.en.yml` to `filename.it.yml`.
- And change the top line of each file from `en:` -> `it:`.
- Translate everything to the right of a colon `:` from English into Italian.
  - `hello: 'hello!'` --> `hello: 'ciao!'`

For `devise.it.yml` you can get the translation from here: https://github.com/tigrish/devise-i18n/blob/master/rails/locales/it.yml or here: https://github.com/plataformatec/devise/wiki/I18n#italian-deviseityml

Lines starting with `#` do not need to be translated.

**Comment by MauroCoppola** [comment]
Great! Thank you for the details :)
