### ISSUE TITLE
Please fix text display issue under Resources > "Download Unisex Restroom Sign"

### ISSUE THREAD

**Issue by hnarasaki** [RefugeRestrooms/refugerestrooms#540]
## Scope / difficulty

Might be easy/Minor display issue.

## Proposal

Please fix this so the text isn't overflowing out of the box.

<img width="1253" alt="screen shot 2018-12-04 at 10 29 20 am" src="https://user-images.githubusercontent.com/29487319/49464532-f4036200-f7af-11e8-8900-f05d5fbe5bb7.png">

## How to actually do this:

Maybe make the box bigger? Not sure if making the font smaller would be too small.

**Comment by DeeDeeG** [comment]
I should be able to take care of this issue. Thank you for reporting it.

(On the other hand, if you would like to solve this issue yourself, @hnarasaki, feel free to say so and I can leave it for you to do!)

**Comment by hnarasaki** [comment]
@DeeDeeG Yes, would you mind leaving it for me to try? :) I just want to finish up the translations one and then I’ll work on this one. Thanks!

**Comment by DeeDeeG** [comment]
No problem!

**Comment by Hkly** [comment]
<img width="1224" alt="Screen Shot 2019-04-24 at 7 48 14 PM" src="https://user-images.githubusercontent.com/5015020/56706475-f6684900-66c9-11e9-9102-635c086c14b9.png">

Would wrapping the text be a reasonable solution? I also added a light grey border to separate the two menu items a bit, but open to other ideas.
