### ISSUE TITLE
Map selection does not close when another is selected

### ISSUE THREAD

**Issue by piercebb** [RefugeRestrooms/refugerestrooms#627]
## Scope / difficulty

Difficulty: easy-medium
Files to change: `maps.js.erb`

## Impact

- Improve user experience when navigating the map view. Currently, bathroom info can "build-up" on the map, like so:

![2020-06-23 13 25 39](https://user-images.githubusercontent.com/65255475/85486851-51245b80-b580-11ea-922e-8edaf6172f28.gif)

- This project will auto-close bathroom markers when a new one is selected, and close the markers when the user clicks "out" of the resource to the map. 

## Rationale

- This change will prevent selections from overlapping and gathering on the map view. 
- It's not the most ideal experience to have to click a small `x` to close the info window every time. 
- Bathroom resources should open and close as a new marker is selected. 
- These changes will more-closely mimic user interactions with other maps, for example:

![2020-06-23 18 32 50](https://user-images.githubusercontent.com/65255475/85486745-1cb09f80-b580-11ea-8d7e-0b0c51eff9f5.gif)

## Proposal

- Add logic to close opened-bathrooms when a new bathroom is selected. 
- Add an on-click listener to the map when the user clicks "out" of the marker to close the opened marker. 

These will prevent bathrooms from crowding the map and overlapping each other. 

## How to actually do this:

- The map view code lives in [`maps.js.erb`](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/javascript/packs/lib/maps.js.erb). 
- To close a marker when another marker is selected:
   -  Add code to close any opened `infoWindows` when a marker is clicked. Probably add the logic in the existing on-click listener [here](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/javascript/packs/lib/maps.js.erb#L83).  
   - Since each `marker` has its own relative `infoWindow`, as opposed to a global `infoWindow`, I think the most recently opened window should be captured in a global variable as suggested [here](https://stackoverflow.com/questions/12621274/close-infowindow-when-another-marker-is-clicked), and then closed as the new marker is selected.
- To close opened markers when the user clicks "out" of the bathroom (i.e. clicks out to the map), an on-click listener should be added to the map as described [here](https://stackoverflow.com/questions/10022873/closing-info-windows-in-google-maps-by-clicking-the-map). 
   - I think this listener should be added within the [`placeMarker()` function](https://github.com/RefugeRestrooms/refugerestrooms/blob/develop/app/javascript/packs/lib/maps.js.erb#L56), so the correct `infoWindow` is closed.

**Comment by DeeDeeG** [comment]
Hi again!

Yes, i see what you mean. This does sound like a reasonable proposal. I wanted to thank you for filling out the issue template, this is a lot of really useful information! I have a full picture of what you mean and how you suggest it could be implemented.

No worries if you aren't, but are you thinking of implementing this yourself? Would you want someone else to pick it up? Either way is fine, just want to make sure two different implementations don't bump into each-other.

**Comment by piercebb** [comment]
I am thinking of implementing this myself. Wanted to write out / get feedback on a proposed implementation before moving forward.

**Comment by DeeDeeG** [comment]
As you show in the GIF in your post, the restroom info panels do overlap a lot. So auto-closing old ones when a new one is clicked makes sense to me.

Any way you want to discuss code changes is okay. Posting "diffs", linking to commits on your fork of Refuge Restrooms on GitHub, opening a PR are all fine.

-- I see there is a PR now. I'll take a look at that.
