### ISSUE TITLE
Thank you message has an error color

### ISSUE THREAD

**Issue by brunoocasali** [RefugeRestrooms/refugerestrooms#652]
After submitting the contact form, the message returned is red (meaning that something is wrong), and should be an info/success color (like blue or green)

![image](https://user-images.githubusercontent.com/4116980/97064803-2292ad80-157f-11eb-8901-3c0d2fff1c36.png)

**Comment by DeeDeeG** [comment]
I have noticed this myself, and I agree it should be another color.
