### ISSUE TITLE
Should the app be served under SSL/TLS?

### ISSUE THREAD

**Issue by f3ndot** [RefugeRestrooms/refugerestrooms#83]
As a bit of a security nut, I'm a big fan of HTTPS since the cost for a certificate is now so cheap and affordable. It might be nice for the users to be offered end-to-end encryption when using the app.

If I understand correctly, Heroku is what's serving the production environment. Unfortunately Heroku likes to be a bit pricy when it comes to SSL/TLS :-1: 

What do y'all think?

**Comment by andrewthelott** [comment]
@kiesia CloudFlare is probably going to improve performance more than hinder it. You're not only serving HTTPS/SPDY to end users but you're also offloading/cache static content onto their CDN.

**Comment by andrewthelott** [comment]
Not only does this have security benefits, but [Google now prefers HTTPS sites](http://googlewebmastercentral.blogspot.co.uk/2014/08/https-as-ranking-signal.html) too.

**Comment by ianyh** [comment]
Any progress on this? This is a likely limitation for further development of the iOS application as in the past few years they have instituted harsher secure connection requirements.

**Comment by tkwidmer** [comment]
Open to investigation more on this if anybody has any input

**Comment by ianyh** [comment]
Looks like Heroku supports non-paid SSL if you acquire a certificate elsewhere. Details are here: https://devcenter.heroku.com/articles/ssl

Could acquire one from Let's Encrypt for free. Details are here: https://letsencrypt.org/getting-started/

I am willing to assist with either or both of these, but would need access to the Heroku app.

**Comment by dannypaz** [comment]
@ianyh +1 for letsencrypt. I think you still technically to `pay` for SSL w/ heroku containers tho :-/. Either you pay for the dyno, or pay for the addon.

```Heroku SSL is included for free on any app that uses paid dynos```

**Comment by ianyh** [comment]
Ah. Good point. Well, depending on what the app's dyno usage looks like l would be willing to cover some cost.

**Comment by mi-wood** [comment]
I'll take a look at this some time this week. I've got all the heroku/dns info, so I should be able to figure out something

**Comment by DeeDeeG** [comment]
Just a comment, Chrome 50 onward have geolocation disabled over http non-secure.
For geolocation buttons on the site, the spinning animations show, and there is a warning message in the console. I'd say most users wouldn't know what's going on.

https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

https://mobiforge.com/news-comment/no-https-then-bye-bye-geolocation-in-chrome-50

**Comment by DeeDeeG** [comment]
Geolocation won't work on Firefox 55+ without HTTPS.

https://www.mozilla.org/en-US/firefox/55.0/releasenotes/
